#ifndef ARCHETYPES_HPP
#define ARCHETYPES_HPP
#include <QMap>
#include <QtGlobal> // quint16
#include <utility>

using Archetype = std::pair<quint16, char const*>;

// clang-format off
static QMap<quint16, char const*> const ARCHETYPES_MAP{
        Archetype{0x666, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Moon Burst")},
	Archetype{0x777, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Solar Sonata")},
	Archetype{0x888, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vow Of Eclipse")},
	Archetype{0x1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ally of Justice")},
	Archetype{0x10, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gusto")},
	Archetype{0x100, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Bonding -")},
	Archetype{0x1002, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "R-Genex")},
	Archetype{0x100a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Steelswarm")},
	Archetype{0x100d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "X-Saber")},
	Archetype{0x101, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Code Talker")},
	Archetype{0x1016, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vehicroid")},
	Archetype{0x1017, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Synchron")},
	Archetype{0x101b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mecha Phantom Beast")},
	Archetype{0x102, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rokket")},
	Archetype{0x102b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Armor Ninja")},
	Archetype{0x103, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Altergeist")},
	Archetype{0x1033, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Assault Blackwing")},
	Archetype{0x1034, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Crystal Beast")},
	Archetype{0x103d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Secret Six Samurai")},
	Archetype{0x104, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Krawler")},
	Archetype{0x1045, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Red Dragon Archfiend")},
	Archetype{0x1046, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fusion Dragon")},
	Archetype{0x1047, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gem-Knight")},
	Archetype{0x1048, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Number C")},
	Archetype{0x104f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "/Assault Mode")},
	Archetype{0x105, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Metaphys")},
	Archetype{0x1050, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Starving Venom")},
	Archetype{0x1052, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gate Guardian")},
	Archetype{0x106, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vendread")},
	Archetype{0x1066, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Symphonic Warrior")},
	Archetype{0x106d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Djinn of Rituals")},
	Archetype{0x106e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spellbook")},
	Archetype{0x106f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heroic Challenger")},
	Archetype{0x107, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "F.A.")},
	Archetype{0x1072, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Geargiano")},
	Archetype{0x1073, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "CXyz")},
	Archetype{0x107a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Noble Knight")},
	Archetype{0x107b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Galaxy-Eyes")},
	Archetype{0x107d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hazy Flame")},
	Archetype{0x107e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "ZW -")},
	Archetype{0x107f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Utopia")},
	Archetype{0x108, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magical Musket")},
	Archetype{0x1081, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fire King Avatar")},
	Archetype{0x1083, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gimmick Puppet")},
	Archetype{0x108a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Traptrix")},
	Archetype{0x109, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "The Weather")},
	Archetype{0x1093, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cyber Dragon")},
	Archetype{0x109a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Superheavy Samurai Soul")},
	Archetype{0x109b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Melodious Maestra")},
	Archetype{0x109c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Stellarknight")},
	Archetype{0x10a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Parshath")},
	Archetype{0x10a2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Magician")},
	Archetype{0x10a4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Winged Kuriboh")},
	Archetype{0x10aa, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Apoqliphort")},
	Archetype{0x10af, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "D/D/D")},
	Archetype{0x10b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tindangle")},
	Archetype{0x10b5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ritual Beast Tamer")},
	Archetype{0x10b7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Outer Entity")},
	Archetype{0x10c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mekk-Knight")},
	Archetype{0x10c0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Familiar-Possessed")},
	Archetype{0x10c1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "PSY-Framegear")},
	Archetype{0x10cd, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Aquaactress")},
	Archetype{0x10cf, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Black Luster Soldier")},
	Archetype{0x10d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mythical Beast")},
	Archetype{0x10d9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shiranui Spectralsword")},
	Archetype{0x10db, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "The Phantom Knights")},
	Archetype{0x10dc, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Super Quantum")},
	Archetype{0x10e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evolution Pill")},
	Archetype{0x10e3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cubic Seed")},
	Archetype{0x10e5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cipher Dragon")},
	Archetype{0x10ec, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Abyss Actor")},
	Archetype{0x10ed, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Subterror Behemoth")},
	Archetype{0x10ee, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "SPYRAL GEAR")},
	Archetype{0x10f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Borrel")},
	Archetype{0x10f2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Pendulum Dragon")},
	Archetype{0x10f3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Predaplant")},
	Archetype{0x10f8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Supreme King Gate")},
	Archetype{0x11, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Karakuri")},
	Archetype{0x110, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Relinquished")},
	Archetype{0x111, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Armed Dragon")},
	Archetype{0x1110, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Eyes Restrict")},
	Archetype{0x1115, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sky Striker Ace")},
	Archetype{0x112, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Knightmare")},
	Archetype{0x1123, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rose Dragon")},
	Archetype{0x113, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Elemental Lord")},
	Archetype{0x1130, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Unchained Soul")},
	Archetype{0x114, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fur Hire")},
	Archetype{0x114b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Numeron Gate")},
	Archetype{0x115, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sky Striker")},
	Archetype{0x1150, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Virtual World Gate")},
	Archetype{0x1157, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sunavalon")},
	Archetype{0x116, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Crusadia")},
	Archetype{0x1164, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "GranSolfachord")},
	Archetype{0x1169, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mystical Beast of the Forest")},
	Archetype{0x117, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Impcantation")},
	Archetype{0x1178, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Barian's")},
	Archetype{0x117f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Welcome Labrynth")},
	Archetype{0x118, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cynet")},
	Archetype{0x1186, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doodle Beast")},
	Archetype{0x119, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Salamangreat")},
	Archetype{0x11a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dinowrestler")},
	Archetype{0x11b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Orcust")},
	Archetype{0x11c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Thunder Dragon")},
	Archetype{0x11d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Forbidden")},
	Archetype{0x11e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Danger!")},
	Archetype{0x11f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nephthys")},
	Archetype{0x12, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Frog")},
	Archetype{0x120, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Prank-Kids")},
	Archetype{0x121, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mayakashi")},
	Archetype{0x122, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Valkyrie")},
	Archetype{0x123, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rose")},
	Archetype{0x124, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Machine Angel")},
	Archetype{0x125, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Smile")},
	Archetype{0x126, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Time Thief")},
	Archetype{0x127, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Infinitrack")},
	Archetype{0x128, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Witchcrafter")},
	Archetype{0x129, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evil Eye")},
	Archetype{0x12a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Endymion")},
	Archetype{0x12b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Marincess")},
	Archetype{0x12c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tenyi")},
	Archetype{0x12d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Simorgh")},
	Archetype{0x12e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fortune Fairy")},
	Archetype{0x12f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Battlewasp")},
	Archetype{0x13, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Meklord")},
	Archetype{0x130, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Unchained")},
	Archetype{0x131, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dream Mirror")},
	Archetype{0x132, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mathmech")},
	Archetype{0x133, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dragonmaid")},
	Archetype{0x134, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Generaider")},
	Archetype{0x135, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "@Ignister")},
	Archetype{0x136, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "A.I.")},
	Archetype{0x137, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ancient Warriors")},
	Archetype{0x138, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Megalith")},
	Archetype{0x139, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Onomat")},
	Archetype{0x13a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Palladium")},
	Archetype{0x13b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rebellion")},
	Archetype{0x13c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Codebreaker")},
	Archetype{0x13d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nemeses")},
	Archetype{0x13e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Barbaros")},
	Archetype{0x13f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Plunder Patroll")},
	Archetype{0x14, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Allure Queen")},
	Archetype{0x140, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Adamancipator")},
	Archetype{0x141, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rikka")},
	Archetype{0x142, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Eldlich")},
	Archetype{0x143, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Eldlixir")},
	Archetype{0x144, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Golden Land")},
	Archetype{0x145, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Phantasm")},
	Archetype{0x146, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dogmatika")},
	Archetype{0x147, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Melffy")},
	Archetype{0x148, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Potan")},
	Archetype{0x149, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Roland")},
	Archetype{0x14a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Appliancer")},
	Archetype{0x14b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Numeron")},
	Archetype{0x14c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fossil")},
	Archetype{0x14d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spiritual Art")},
	Archetype{0x14e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dual Avatar")},
	Archetype{0x14f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tri-Brigade")},
	Archetype{0x15, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "B.E.S.")},
	Archetype{0x150, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Virtual World")},
	Archetype{0x1509, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Barian's")},
	Archetype{0x150c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Phantom Butterfly")},
	Archetype{0x150e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cat Girl")},
	Archetype{0x151, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Drytron")},
	Archetype{0x1512, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Royal Cookpal")},
	Archetype{0x1517, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doll Monster")},
	Archetype{0x1518, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doodle Beast")},
	Archetype{0x151a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Earthbound")},
	Archetype{0x151b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magic Elf")},
	Archetype{0x152, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magistus")},
	Archetype{0x1521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fossil Knight")},
	Archetype{0x1524, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Granel Attack")},
	Archetype{0x152c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Jester Puppet")},
	Archetype{0x152f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Champion")},
	Archetype{0x153, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ki-sikil")},
	Archetype{0x1530, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Clock Knight")},
	Archetype{0x1538, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Stray Cat")},
	Archetype{0x154, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Lil-la")},
	Archetype{0x1541, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Quiz Panel")},
	Archetype{0x1549, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Skiel Attack")},
	Archetype{0x154a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Angel")},
	Archetype{0x154d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spell Spice")},
	Archetype{0x154e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spirit Gem")},
	Archetype{0x155, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evil★Twin")},
	Archetype{0x1550, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Pendulumstatue")},
	Archetype{0x1555, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tachyon Dragon")},
	Archetype{0x155a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "\" V \"/\" V \"")},
	Archetype{0x155d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "White Knight")},
	Archetype{0x156, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Live☆Twin")},
	Archetype{0x1560, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Wisel Attack")},
	Archetype{0x157, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sun")},
	Archetype{0x158, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Springans")},
	Archetype{0x159, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Myutant")},
	Archetype{0x15a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "S-Force")},
	Archetype{0x15b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Starry Knight")},
	Archetype{0x15c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doll Monster")},
	Archetype{0x15d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rank-Down-Magic")},
	Archetype{0x15e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Amazement")},
	Archetype{0x15f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Attraction")},
	Archetype{0x16, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "roid")},
	Archetype{0x160, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Branded")},
	Archetype{0x161, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "War Rock")},
	Archetype{0x162, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Materiactor")},
	Archetype{0x163, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ogdoadic")},
	Archetype{0x164, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Solfachord")},
	Archetype{0x165, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ursarctic")},
	Archetype{0x166, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Despia")},
	Archetype{0x167, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magikey")},
	Archetype{0x168, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gunkan")},
	Archetype{0x169, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "of the Forest")},
	Archetype{0x16a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Stealth Kragen")},
	Archetype{0x16b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Numerounius")},
	Archetype{0x16c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Number")},
	Archetype{0x16d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Swordsoul")},
	Archetype{0x16e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Icejade")},
	Archetype{0x16f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Floowandereeze")},
	Archetype{0x17, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Synchro")},
	Archetype{0x170, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Topologic")},
	Archetype{0x171, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hyperion")},
	Archetype{0x172, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Beetrooper")},
	Archetype{0x173, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "P.U.N.K.")},
	Archetype{0x174, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Exosister")},
	Archetype{0x174, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Exosister")},
	Archetype{0x175, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dinomorphia")},
	Archetype{0x176, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Lady of Lament")},
	Archetype{0x177, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Seventh")},
	Archetype{0x178, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Barian")},
	Archetype{0x179, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kairyu-Shin")},
	Archetype{0x17a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sea Stealth")},
	Archetype{0x17b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Therion")},
	Archetype{0x17c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Scareclaw")},
	Archetype{0x17d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Libromancer")},
	Archetype{0x17e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vaylantz")},
	Archetype{0x17f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Labrynth")},
	Archetype{0x18, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cloudian")},
	Archetype{0x180, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Runick")},
	Archetype{0x181, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spright")},
	Archetype{0x182, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tearlaments")},
	Archetype{0x183, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vernusylph")},
	Archetype{0x184, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mokey Mokey")},
	Archetype{0x185, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Wingman")},
	Archetype{0x186, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doodle")},
	Archetype{0x187, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "G Golem")},
	Archetype{0x188, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rainbow Bridge")},
	Archetype{0x189, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Byssted")},
	Archetype{0x189, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Bystial")},
	Archetype{0x18a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kashtira")},
	Archetype{0x18a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kshatri-La")},
	Archetype{0x18b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ghoti")},
	Archetype{0x18c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rescue-ACE")},
	Archetype{0x18d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Purery")},
	Archetype{0x18d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Purrely")},
	Archetype{0x18e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mikanko")},
	Archetype{0x18f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Aquamirror")},
	Archetype{0x19, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gladiator Beast")},
	Archetype{0x190, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Firewall")},
	Archetype{0x191, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Manadome")},
	Archetype{0x192, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nemurelia")},
	Archetype{0x193, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gold Pride")},
	Archetype{0x194, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Labyrinth Wall")},
	Archetype{0x195, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Favorite")},
	Archetype{0x196, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vanquish Soul")},
	Archetype{0x197, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nouvelles")},
	Archetype{0x198, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Recipe")},
	Archetype{0x199, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Visas")},
	Archetype{0x1a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Scorpion")},
	Archetype{0x1a0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Toy")},
	Archetype{0x1a1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tenpai Dragon")},
	Archetype{0x1a2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sangen")},
	Archetype{0x1a3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Raika")},
	Archetype{0x1a4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Salamandra")},
	Archetype{0x1a5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ashened")},
	Archetype{0x1a6, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Millennium")},
	Archetype{0x1a7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Exodo")},
	Archetype{0x1b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Phantom Beast")},
	Archetype{0x1c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spirit Message")},
	Archetype{0x1d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Koa'ki Meiru")},
	Archetype{0x1e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Chrysalis")},
	Archetype{0x1f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Neo-Spacian")},
	Archetype{0x2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Genex")},
	Archetype{0x20, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shien")},
	Archetype{0x2002, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Genex Ally")},
	Archetype{0x2016, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Speedroid")},
	Archetype{0x2017, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Synchro Dragon")},
	Archetype{0x2033, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Blackwing Tamer")},
	Archetype{0x2034, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ultimate Crystal")},
	Archetype{0x2048, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Number S")},
	Archetype{0x2066, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magnet Warrior")},
	Archetype{0x206f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heroic Champion")},
	Archetype{0x2073, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Xyz Dragon")},
	Archetype{0x207a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Noble Arms")},
	Archetype{0x207e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "ZS -")},
	Archetype{0x207f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Utopic Future")},
	Archetype{0x2093, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cyber Angel")},
	Archetype{0x209b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Melodious Songstress")},
	Archetype{0x20a2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magician Girl")},
	Archetype{0x20b5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spiritual Beast")},
	Archetype{0x20b7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Elder Entity")},
	Archetype{0x20cd, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Aquarium")},
	Archetype{0x20dc, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Super Quantal Mech Beast")},
	Archetype{0x20ec, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Abyss Script")},
	Archetype{0x20ee, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "SPYRAL MISSION")},
	Archetype{0x20f2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Pendulumgraph")},
	Archetype{0x20f8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Supreme King Dragon")},
	Archetype{0x21, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Earthbound Immortal")},
	Archetype{0x2157, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sunvine")},
	Archetype{0x2169, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mystical Spirit of the Forest")},
	Archetype{0x2178, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Battleguard")},
	Archetype{0x2186, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doodlebook")},
	Archetype{0x22, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Jurrac")},
	Archetype{0x23, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Malefic")},
	Archetype{0x24, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Scrap")},
	Archetype{0x25, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Iron Chain")},
	Archetype{0x2509, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Battleguard")},
	Archetype{0x2517, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doll Part")},
	Archetype{0x2521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cenozoic")},
	Archetype{0x2524, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Granel Guard")},
	Archetype{0x2549, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Skiel Guard")},
	Archetype{0x254a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Celestial")},
	Archetype{0x2560, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Wisel Guard")},
	Archetype{0x26, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Morphtronic")},
	Archetype{0x27, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "T.G.")},
	Archetype{0x28, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Batteryman")},
	Archetype{0x29, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dragunity")},
	Archetype{0x293, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Visas")},
	Archetype{0x294, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Counter")},
	Archetype{0x295, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Battlin' Boxing")},
	Archetype{0x2a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Naturia")},
	Archetype{0x2b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ninja")},
	Archetype{0x2c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Flamvell")},
	Archetype{0x2d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nitro")},
	Archetype{0x2e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gravekeeper's")},
	Archetype{0x2f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ice Barrier")},
	Archetype{0x3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Horus the Black Flame Dragon")},
	Archetype{0x30, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vylon")},
	Archetype{0x3008, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Elemental HERO")},
	Archetype{0x300d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "XX-Saber")},
	Archetype{0x3013, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Meklord Emperor")},
	Archetype{0x3042, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nordic Ascendant")},
	Archetype{0x304e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evoltile")},
	Archetype{0x307b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Galaxy-Eyes Tachyon Dragon")},
	Archetype{0x30a2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Magician Girl")},
	Archetype{0x30b5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spiritual Beast Tamer")},
	Archetype{0x31, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fortune Lady")},
	Archetype{0x314d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spiritual Earth Art")},
	Archetype{0x316, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Darkness")},
	Archetype{0x32, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Volcanic")},
	Archetype{0x33, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Blackwing")},
	Archetype{0x34, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Crystal")},
	Archetype{0x35, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fabled")},
	Archetype{0x351a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Earthbound Servant")},
	Archetype{0x3521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cenozoic Fossil Knight")},
	Archetype{0x36, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Machina")},
	Archetype{0x37, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mist Valley")},
	Archetype{0x38, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Lightsworn")},
	Archetype{0x39, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Laval")},
	Archetype{0x3a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gishki")},
	Archetype{0x3b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Red-Eyes")},
	Archetype{0x3c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Reptilianne")},
	Archetype{0x3d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Six Samurai")},
	Archetype{0x3e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Worm")},
	Archetype{0x3f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Majestic")},
	Archetype{0x4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Amazoness")},
	Archetype{0x40, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Forbidden One")},
	Archetype{0x400d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Elementsaber")},
	Archetype{0x407a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Infernoble")},
	Archetype{0x4093, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cyberdark")},
	Archetype{0x40b5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ritual Beast Ulti-")},
	Archetype{0x40b7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Old Entity")},
	Archetype{0x40ec, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Abyss Costume")},
	Archetype{0x41, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "LV")},
	Archetype{0x4157, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sunseed")},
	Archetype{0x42, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nordic")},
	Archetype{0x43, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Junk")},
	Archetype{0x44, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "The Agent")},
	Archetype{0x45, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Archfiend")},
	Archetype{0x4521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mezozoic")},
	Archetype{0x4524, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Granel Top")},
	Archetype{0x4549, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Skiel Top")},
	Archetype{0x4560, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Wisel Top")},
	Archetype{0x46, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Polymerization|Fusion")},
	Archetype{0x47, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gem-")},
	Archetype{0x48, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Number")},
	Archetype{0x49, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Skyblaster")},
	Archetype{0x4a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Timelord")},
	Archetype{0x4b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Aesir")},
	Archetype{0x4c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Trap Hole")},
	Archetype{0x4d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Beast's Battle")},
	Archetype{0x4e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evol")},
	Archetype{0x4f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Lucius")},
	Archetype{0x5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Arcana Force")},
	Archetype{0x50, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Venom")},
	Archetype{0x500, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Speed Spell")},
	Archetype{0x5008, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vision HERO")},
	Archetype{0x501, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Alchemy Beast")},
	Archetype{0x502, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Alligator")},
	Archetype{0x503, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Anti")},
	Archetype{0x5034, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Advanced Crystal Beast")},
	Archetype{0x504, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Assassin")},
	Archetype{0x5042, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nordic Relic")},
	Archetype{0x5048, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Number C39")},
	Archetype{0x504e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evolzar")},
	Archetype{0x505, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Astral")},
	Archetype{0x506, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Atlandis")},
	Archetype{0x507, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Attack")},
	Archetype{0x507a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Infernoble Knight")},
	Archetype{0x508, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Baby")},
	Archetype{0x509, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Barian")},
	Archetype{0x50b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Beastborg")},
	Archetype{0x50c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Butterfly")},
	Archetype{0x50d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Carrier")},
	Archetype{0x50e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cat")},
	Archetype{0x50f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cicada")},
	Archetype{0x51, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gadget")},
	Archetype{0x510, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Clear")},
	Archetype{0x511, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Comics Hero")},
	Archetype{0x512, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cookpal")},
	Archetype{0x513, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dart")},
	Archetype{0x514, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dice")},
	Archetype{0x514d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spiritual Fire Art")},
	Archetype{0x515, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dizzy")},
	Archetype{0x516, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dog")},
	Archetype{0x517, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doll")},
	Archetype{0x518, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Doodle")},
	Archetype{0x519, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dyson")},
	Archetype{0x51a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Earth")},
	Archetype{0x51b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Elf")},
	Archetype{0x51d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fairy")},
	Archetype{0x51e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Forbidden Beast")},
	Archetype{0x51f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Forest")},
	Archetype{0x52, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Guardian")},
	Archetype{0x520, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fortune Fairy")},
	Archetype{0x521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gaia the Dragon Champion")},
	Archetype{0x522, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gorgonic")},
	Archetype{0x523, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Goyo")},
	Archetype{0x524, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Granel")},
	Archetype{0x525, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Guard")},
	Archetype{0x526, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Guts Master")},
	Archetype{0x527, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hand")},
	Archetype{0x528, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heart Monster")},
	Archetype{0x529, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heavy Industry")},
	Archetype{0x52a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Inu")},
	Archetype{0x52b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ivy")},
	Archetype{0x52c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Jester")},
	Archetype{0x52d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Jutte")},
	Archetype{0x52e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kabuki Stage")},
	Archetype{0x52f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "King")},
	Archetype{0x53, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Constellar")},
	Archetype{0x530, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Knight")},
	Archetype{0x531, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Koala")},
	Archetype{0x533, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Landstar")},
	Archetype{0x534, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magnet")},
	Archetype{0x535, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mantis")},
	Archetype{0x536, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mosquito")},
	Archetype{0x537, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Motor")},
	Archetype{0x538, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Neko")},
	Archetype{0x53b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Numeronius")},
	Archetype{0x53c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Papillon")},
	Archetype{0x53d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Parasite")},
	Archetype{0x53e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Pixie")},
	Archetype{0x53f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Priestess")},
	Archetype{0x54, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gagaga")},
	Archetype{0x540, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Puppet")},
	Archetype{0x541, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Quiz")},
	Archetype{0x542, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Raccoon")},
	Archetype{0x543, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Red")},
	Archetype{0x545, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Seal")},
	Archetype{0x546, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shaman")},
	Archetype{0x547, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shark")},
	Archetype{0x548, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shining")},
	Archetype{0x549, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Skiel")},
	Archetype{0x54a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sky")},
	Archetype{0x54b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Slime")},
	Archetype{0x54c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sphere")},
	Archetype{0x54d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spice")},
	Archetype{0x54e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spirit")},
	Archetype{0x54f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Starship")},
	Archetype{0x55, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Photon")},
	Archetype{0x550, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Statue")},
	Archetype{0x551, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Stone")},
	Archetype{0x552, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Strain")},
	Archetype{0x5521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mezozoic Fossil Knight")},
	Archetype{0x555, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tachyon")},
	Archetype{0x556, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Thorn Prisoner")},
	Archetype{0x557, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Top")},
	Archetype{0x558, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Toy (Arc-V)")},
	Archetype{0x559, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Toy")},
	Archetype{0x55a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "V")},
	Archetype{0x55c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vigilante")},
	Archetype{0x55d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "White")},
	Archetype{0x55f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sinister Doctrine")},
	Archetype{0x56, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Inzektor")},
	Archetype{0x560, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Wisel")},
	Archetype{0x561, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Yubel")},
	Archetype{0x562, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "∞")},
	Archetype{0x563, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Yomi")},
	Archetype{0x564, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shogi|Line Monster")},
	Archetype{0x565, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hunder")},
	Archetype{0x566, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heraldic")},
	Archetype{0x567, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hell")},
	Archetype{0x568, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "C")},
	Archetype{0x569, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Eco Spell")},
	Archetype{0x56a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Junk Robot")},
	Archetype{0x56b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "W")},
	Archetype{0x56c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "X")},
	Archetype{0x56d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Y")},
	Archetype{0x56e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Z")},
	Archetype{0x56f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Mummy")},
	Archetype{0x57, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Resonator")},
	Archetype{0x570, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tentacluster")},
	Archetype{0x571, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Monarch (monster)")},
	Archetype{0x572, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mirror Imagine")},
	Archetype{0x573, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Helixx")},
	Archetype{0x574, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sunavalon")},
	Archetype{0x575, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sunvine")},
	Archetype{0x576, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Starving Venemy")},
	Archetype{0x577, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hydradrive")},
	Archetype{0x578, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Armatos Legio")},
	Archetype{0x579, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "D-Scale")},
	Archetype{0x57a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Appliancer")},
	Archetype{0x57b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Topologina")},
	Archetype{0x58, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Wind-Up")},
	Archetype{0x580, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Stormrider")},
	Archetype{0x581, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Drone")},
	Archetype{0x583, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mask")},
	Archetype{0x59, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gogogo")},
	Archetype{0x5a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Penguin")},
	Archetype{0x5b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Inmato")},
	Archetype{0x5c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sphinx")},
	Archetype{0x5d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ultimate Insect")},
	Archetype{0x5e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Mimic")},
	Archetype{0x5f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mystic Swordsman")},
	Archetype{0x6, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark World")},
	Archetype{0x60, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Bamboo Sword")},
	Archetype{0x600, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Tuner")},
	Archetype{0x6008, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evil HERO")},
	Archetype{0x601, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Synchro")},
	Archetype{0x6013, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Meklord Army")},
	Archetype{0x6042, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nordic Beast")},
	Archetype{0x604e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Evolsaur")},
	Archetype{0x607a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Infernoble Arms")},
	Archetype{0x61, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ninjitsu Art")},
	Archetype{0x614d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spiritual Water Art")},
	Archetype{0x62, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Toon")},
	Archetype{0x63, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Reactor")},
	Archetype{0x64, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Harpie")},
	Archetype{0x65, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Infestation")},
	Archetype{0x66, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Warrior")},
	Archetype{0x67, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Iron")},
	Archetype{0x67, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Koala")},
	Archetype{0x68, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kangaroo")},
	Archetype{0x68, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Tin")},
	Archetype{0x69, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hieratic")},
	Archetype{0x6a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Butterspy")},
	Archetype{0x6b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Bounzer")},
	Archetype{0x6c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Lightray")},
	Archetype{0x6d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Djinn")},
	Archetype{0x6e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Prophecy")},
	Archetype{0x6f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heroic")},
	Archetype{0x7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ancient Gear")},
	Archetype{0x70, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Chronomaly")},
	Archetype{0x71, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Madolche")},
	Archetype{0x72, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Geargia")},
	Archetype{0x73, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Xyz")},
	Archetype{0x74, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Mermail")},
	Archetype{0x75, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Abyss-")},
	Archetype{0x76, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heraldic Beast")},
	Archetype{0x77, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Atlantean")},
	Archetype{0x78, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nimble")},
	Archetype{0x79, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fire Fist")},
	Archetype{0x7a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Noble")},
	Archetype{0x7b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Galaxy")},
	Archetype{0x7c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fire Formation")},
	Archetype{0x7d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hazy")},
	Archetype{0x7e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Zexal")},
	Archetype{0x7f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Utopic")},
	Archetype{0x8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "HERO")},
	Archetype{0x80, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Duston")},
	Archetype{0x81, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fire King")},
	Archetype{0x82, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dododo")},
	Archetype{0x83, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Puppet")},
	Archetype{0x84, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Battlin' Boxer")},
	Archetype{0x85, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Super Defense Robot")},
	Archetype{0x8521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Paleozoic")},
	Archetype{0x8524, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Granel Carrier")},
	Archetype{0x8549, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Skiel Carrier")},
	Archetype{0x8560, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Wisel Carrier")},
	Archetype{0x86, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Star Seraph")},
	Archetype{0x87, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Umbral Horror")},
	Archetype{0x88, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Bujin")},
	Archetype{0x89, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Hole")},
	Archetype{0x8a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Envy")},
	Archetype{0x8b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Malicevorous")},
	Archetype{0x8c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Druid")},
	Archetype{0x8d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ghostrick")},
	Archetype{0x8e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Vampire")},
	Archetype{0x8f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Zubaba")},
	Archetype{0x9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Neos")},
	Archetype{0x90, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Sylvan")},
	Archetype{0x9013, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Meklord Astro")},
	Archetype{0x91, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Necrovalley")},
	Archetype{0x92, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Heraldry")},
	Archetype{0x93, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cyber")},
	Archetype{0x94, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cybernetic")},
	Archetype{0x95, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Rank-Up-Magic")},
	Archetype{0x9521, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Paleozoic Fossil Knight")},
	Archetype{0x96, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fishborg")},
	Archetype{0x97, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Artifact")},
	Archetype{0x98, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magician")},
	Archetype{0x99, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Odd-Eyes")},
	Archetype{0x9a, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Superheavy Samurai")},
	Archetype{0x9b, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Melodious")},
	Archetype{0x9c, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "tellarknight")},
	Archetype{0x9d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shaddoll")},
	Archetype{0x9e, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Yang Zing")},
	Archetype{0x9f, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Performapal")},
	Archetype{0xa, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "lswarm")},
	Archetype{0xa0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Legendary Knight")},
	Archetype{0xa008, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Masked HERO")},
	Archetype{0xa042, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nordic Alfar")},
	Archetype{0xa1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Legendary Dragon")},
	Archetype{0xa14d, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Spiritual Wind Art")},
	Archetype{0xa2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magician")},
	Archetype{0xa3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Stardust")},
	Archetype{0xa4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kuriboh")},
	Archetype{0xa5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Change")},
	Archetype{0xa6, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "sprout")},
	Archetype{0xa7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Artorigus")},
	Archetype{0xa8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Laundsallyn")},
	Archetype{0xa9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Fluffal")},
	Archetype{0xaa, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Qli")},
	Archetype{0xab, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Deskbot")},
	Archetype{0xac, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Goblin")},
	Archetype{0xad, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Frightfur")},
	Archetype{0xae, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dark Contract")},
	Archetype{0xaf, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "D/D")},
	Archetype{0xb, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Infernity")},
	Archetype{0xb0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gottoms")},
	Archetype{0xb1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Burning Abyss")},
	Archetype{0xb2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "U.A.")},
	Archetype{0xb3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Yosenju")},
	Archetype{0xb4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Nekroz")},
	Archetype{0xb5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ritual Beast")},
	Archetype{0xb7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Entity")},
	Archetype{0xb9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Blaze Accelerator")},
	Archetype{0xba, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Raidraptor")},
	Archetype{0xbb, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Infernoid")},
	Archetype{0xbc, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Jinzo")},
	Archetype{0xbd, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gaia The Fierce Knight")},
	Archetype{0xbe, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Monarch")},
	Archetype{0xbf, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Charmer")},
	Archetype{0xc, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Alien")},
	Archetype{0xc0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Possessed")},
	Archetype{0xc008, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Destiny HERO")},
	Archetype{0xc1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "PSY-Frame")},
	Archetype{0xc2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Power Tool")},
	Archetype{0xc3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Edge Imp")},
	Archetype{0xc4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Zefra")},
	Archetype{0xc5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Void")},
	Archetype{0xc6, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Performage")},
	Archetype{0xc7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dracoslayer")},
	Archetype{0xc8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Igknight")},
	Archetype{0xc9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Aroma")},
	Archetype{0xca, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Empowered Warrior")},
	Archetype{0xcb, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Aether")},
	Archetype{0xcc, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Prediction Princess")},
	Archetype{0xcd, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Aqua")},
	Archetype{0xcf, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Chaos")},
	Archetype{0xd, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Saber")},
	Archetype{0xd0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Majespecter")},
	Archetype{0xd1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Graydle")},
	Archetype{0xd2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kozmo")},
	Archetype{0xd3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Kaiju")},
	Archetype{0xd4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Paleozoic")},
	Archetype{0xd5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dante")},
	Archetype{0xd6, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Destruction Sword")},
	Archetype{0xd7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Buster Blader")},
	Archetype{0xd8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dinomist")},
	Archetype{0xd9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Shiranui")},
	Archetype{0xda, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Dracoverlord")},
	Archetype{0xdb, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Phantom Knights")},
	Archetype{0xdc, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Super Quant")},
	Archetype{0xdd, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Blue-Eyes")},
	Archetype{0xde, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Exodia")},
	Archetype{0xdf, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Lunalight")},
	Archetype{0xe, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Watt")},
	Archetype{0xe0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Amorphage")},
	Archetype{0xe1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Metalfoes")},
	Archetype{0xe2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Triamid")},
	Archetype{0xe3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cubic")},
	Archetype{0xe4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Celtic Guard")},
	Archetype{0xe5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Cipher")},
	Archetype{0xe6, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Flower Cardian")},
	Archetype{0xe7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Silent Swordsman")},
	Archetype{0xe8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Silent Magician")},
	Archetype{0xe9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Magna Warrior")},
	Archetype{0xea, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Crystron")},
	Archetype{0xeb, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Chemicritter")},
	Archetype{0xec, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Abyss")},
	Archetype{0xed, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Subterror")},
	Archetype{0xee, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "SPYRAL")},
	Archetype{0xef, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Darklord")},
	Archetype{0xf, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Ojama")},
	Archetype{0xf0, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Windwitch")},
	Archetype{0xf1, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Zoodiac")},
	Archetype{0xf2, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Pendulum")},
	Archetype{0xf3, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Predap")},
	Archetype{0xf4, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Invoked")},
	Archetype{0xf5, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gandora")},
	Archetype{0xf6, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Skyscraper")},
	Archetype{0xf7, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Lyrilusc")},
	Archetype{0xf8, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Supreme King")},
	Archetype{0xf9, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "True Draco|True King")},
	Archetype{0xfa, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Phantasm Spiral")},
	Archetype{0xfb, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Trickstar")},
	Archetype{0xfc, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Gouki")},
	Archetype{0xfd, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "World Chalice")},
	Archetype{0xfe, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "World Legacy")},
	Archetype{0xff, QT_TRANSLATE_NOOP("DatabaseEditorWidget", "Clear Wing")},
};
// clang-format on

#endif // ARCHETYPES_HPP
