#ifndef ARCHETYPES_HPP
#define ARCHETYPES_HPP
#include <QMap>
#include <QtGlobal> // quint16
#include <utility>

using Archetype = std::pair<quint16, char const*>;

static QMap<quint16, char const*> const ARCHETYPES_MAP{
	Archetype{0x1, QT_TRANSLATE_NOOP("MainWindow", "Ally of Justice")},
	Archetype{0x10, QT_TRANSLATE_NOOP("MainWindow", "Gusto")},
	Archetype{0x100, QT_TRANSLATE_NOOP("MainWindow", "Bonding -")},
	Archetype{0x1002, QT_TRANSLATE_NOOP("MainWindow", "R-Genex")},
	Archetype{0x100a, QT_TRANSLATE_NOOP("MainWindow", "Steelswarm")},
	Archetype{0x100d, QT_TRANSLATE_NOOP("MainWindow", "X-Saber")},
	Archetype{0x101, QT_TRANSLATE_NOOP("MainWindow", "Code Talker")},
	Archetype{0x1016, QT_TRANSLATE_NOOP("MainWindow", "Vehicroid")},
	Archetype{0x1017, QT_TRANSLATE_NOOP("MainWindow", "Synchron")},
	Archetype{0x101b, QT_TRANSLATE_NOOP("MainWindow", "Mecha Phantom Beast")},
	Archetype{0x102, QT_TRANSLATE_NOOP("MainWindow", "Rokket")},
	Archetype{0x102b, QT_TRANSLATE_NOOP("MainWindow", "Armor Ninja")},
	Archetype{0x103, QT_TRANSLATE_NOOP("MainWindow", "Altergeist")},
	Archetype{0x1033, QT_TRANSLATE_NOOP("MainWindow", "Assault Blackwing")},
	Archetype{0x1034, QT_TRANSLATE_NOOP("MainWindow", "Crystal Beast")},
	Archetype{0x103d, QT_TRANSLATE_NOOP("MainWindow", "Secret Six Samurai")},
	Archetype{0x104, QT_TRANSLATE_NOOP("MainWindow", "Krawler")},
	Archetype{0x1045, QT_TRANSLATE_NOOP("MainWindow", "Red Dragon Archfiend")},
	Archetype{0x1046, QT_TRANSLATE_NOOP("MainWindow", "Fusion Dragon")},
	Archetype{0x1047, QT_TRANSLATE_NOOP("MainWindow", "Gem-Knight")},
	Archetype{0x1048, QT_TRANSLATE_NOOP("MainWindow", "Number C")},
	Archetype{0x104f, QT_TRANSLATE_NOOP("MainWindow", "/Assault Mode")},
	Archetype{0x105, QT_TRANSLATE_NOOP("MainWindow", "Metaphys")},
	Archetype{0x1050, QT_TRANSLATE_NOOP("MainWindow", "Starving Venom")},
	Archetype{0x1052, QT_TRANSLATE_NOOP("MainWindow", "Gate Guardian")},
	Archetype{0x106, QT_TRANSLATE_NOOP("MainWindow", "Vendread")},
	Archetype{0x1066, QT_TRANSLATE_NOOP("MainWindow", "Symphonic Warrior")},
	Archetype{0x106d, QT_TRANSLATE_NOOP("MainWindow", "Djinn of Rituals")},
	Archetype{0x106e, QT_TRANSLATE_NOOP("MainWindow", "Spellbook")},
	Archetype{0x106f, QT_TRANSLATE_NOOP("MainWindow", "Heroic Challenger")},
	Archetype{0x107, QT_TRANSLATE_NOOP("MainWindow", "F.A.")},
	Archetype{0x1072, QT_TRANSLATE_NOOP("MainWindow", "Geargiano")},
	Archetype{0x1073, QT_TRANSLATE_NOOP("MainWindow", "CXyz")},
	Archetype{0x107a, QT_TRANSLATE_NOOP("MainWindow", "Noble Knight")},
	Archetype{0x107b, QT_TRANSLATE_NOOP("MainWindow", "Galaxy-Eyes")},
	Archetype{0x107d, QT_TRANSLATE_NOOP("MainWindow", "Hazy Flame")},
	Archetype{0x107e, QT_TRANSLATE_NOOP("MainWindow", "ZW -")},
	Archetype{0x107f, QT_TRANSLATE_NOOP("MainWindow", "Utopia")},
	Archetype{0x108, QT_TRANSLATE_NOOP("MainWindow", "Magical Musket")},
	Archetype{0x1081, QT_TRANSLATE_NOOP("MainWindow", "Fire King Avatar")},
	Archetype{0x1083, QT_TRANSLATE_NOOP("MainWindow", "Gimmick Puppet")},
	Archetype{0x108a, QT_TRANSLATE_NOOP("MainWindow", "Traptrix")},
	Archetype{0x109, QT_TRANSLATE_NOOP("MainWindow", "The Weather")},
	Archetype{0x1093, QT_TRANSLATE_NOOP("MainWindow", "Cyber Dragon")},
	Archetype{0x109a, QT_TRANSLATE_NOOP("MainWindow", "Superheavy Samurai Soul")},
	Archetype{0x109b, QT_TRANSLATE_NOOP("MainWindow", "Melodious Maestra")},
	Archetype{0x109c, QT_TRANSLATE_NOOP("MainWindow", "Stellarknight")},
	Archetype{0x10a, QT_TRANSLATE_NOOP("MainWindow", "Parshath")},
	Archetype{0x10a2, QT_TRANSLATE_NOOP("MainWindow", "Dark Magician")},
	Archetype{0x10a4, QT_TRANSLATE_NOOP("MainWindow", "Winged Kuriboh")},
	Archetype{0x10aa, QT_TRANSLATE_NOOP("MainWindow", "Apoqliphort")},
	Archetype{0x10af, QT_TRANSLATE_NOOP("MainWindow", "D/D/D")},
	Archetype{0x10b, QT_TRANSLATE_NOOP("MainWindow", "Tindangle")},
	Archetype{0x10b5, QT_TRANSLATE_NOOP("MainWindow", "Ritual Beast Tamer")},
	Archetype{0x10b7, QT_TRANSLATE_NOOP("MainWindow", "Outer Entity")},
	Archetype{0x10c, QT_TRANSLATE_NOOP("MainWindow", "Mekk-Knight")},
	Archetype{0x10c0, QT_TRANSLATE_NOOP("MainWindow", "Familiar-Possessed")},
	Archetype{0x10c1, QT_TRANSLATE_NOOP("MainWindow", "PSY-Framegear")},
	Archetype{0x10cd, QT_TRANSLATE_NOOP("MainWindow", "Aquaactress")},
	Archetype{0x10cf, QT_TRANSLATE_NOOP("MainWindow", "Black Luster Soldier")},
	Archetype{0x10d, QT_TRANSLATE_NOOP("MainWindow", "Mythical Beast")},
	Archetype{0x10d9, QT_TRANSLATE_NOOP("MainWindow", "Shiranui Spectralsword")},
	Archetype{0x10db, QT_TRANSLATE_NOOP("MainWindow", "The Phantom Knights")},
	Archetype{0x10dc, QT_TRANSLATE_NOOP("MainWindow", "Super Quantum")},
	Archetype{0x10e, QT_TRANSLATE_NOOP("MainWindow", "Evolution Pill")},
	Archetype{0x10e3, QT_TRANSLATE_NOOP("MainWindow", "Cubic Seed")},
	Archetype{0x10e5, QT_TRANSLATE_NOOP("MainWindow", "Cipher Dragon")},
	Archetype{0x10ec, QT_TRANSLATE_NOOP("MainWindow", "Abyss Actor")},
	Archetype{0x10ed, QT_TRANSLATE_NOOP("MainWindow", "Subterror Behemoth")},
	Archetype{0x10ee, QT_TRANSLATE_NOOP("MainWindow", "SPYRAL GEAR")},
	Archetype{0x10f, QT_TRANSLATE_NOOP("MainWindow", "Borrel")},
	Archetype{0x10f2, QT_TRANSLATE_NOOP("MainWindow", "Pendulum Dragon")},
	Archetype{0x10f3, QT_TRANSLATE_NOOP("MainWindow", "Predaplant")},
	Archetype{0x10f8, QT_TRANSLATE_NOOP("MainWindow", "Supreme King Gate")},
	Archetype{0x11, QT_TRANSLATE_NOOP("MainWindow", "Karakuri")},
	Archetype{0x110, QT_TRANSLATE_NOOP("MainWindow", "Relinquished")},
	Archetype{0x111, QT_TRANSLATE_NOOP("MainWindow", "Armed Dragon")},
	Archetype{0x1110, QT_TRANSLATE_NOOP("MainWindow", "Eyes Restrict")},
	Archetype{0x1115, QT_TRANSLATE_NOOP("MainWindow", "Sky Striker Ace")},
	Archetype{0x112, QT_TRANSLATE_NOOP("MainWindow", "Knightmare")},
	Archetype{0x1123, QT_TRANSLATE_NOOP("MainWindow", "Rose Dragon")},
	Archetype{0x113, QT_TRANSLATE_NOOP("MainWindow", "Elemental Lord")},
	Archetype{0x1130, QT_TRANSLATE_NOOP("MainWindow", "Unchained Soul")},
	Archetype{0x114, QT_TRANSLATE_NOOP("MainWindow", "Fur Hire")},
	Archetype{0x114b, QT_TRANSLATE_NOOP("MainWindow", "Numeron Gate")},
	Archetype{0x115, QT_TRANSLATE_NOOP("MainWindow", "Sky Striker")},
	Archetype{0x1150, QT_TRANSLATE_NOOP("MainWindow", "Virtual World Gate")},
	Archetype{0x1157, QT_TRANSLATE_NOOP("MainWindow", "Sunavalon")},
	Archetype{0x116, QT_TRANSLATE_NOOP("MainWindow", "Crusadia")},
	Archetype{0x1164, QT_TRANSLATE_NOOP("MainWindow", "GranSolfachord")},
	Archetype{0x1169, QT_TRANSLATE_NOOP("MainWindow", "Mystical Beast of the Forest")},
	Archetype{0x117, QT_TRANSLATE_NOOP("MainWindow", "Impcantation")},
	Archetype{0x1178, QT_TRANSLATE_NOOP("MainWindow", "Barian's")},
	Archetype{0x117f, QT_TRANSLATE_NOOP("MainWindow", "Welcome Labrynth")},
	Archetype{0x118, QT_TRANSLATE_NOOP("MainWindow", "Cynet")},
	Archetype{0x1186, QT_TRANSLATE_NOOP("MainWindow", "Doodle Beast")},
	Archetype{0x119, QT_TRANSLATE_NOOP("MainWindow", "Salamangreat")},
	Archetype{0x11a, QT_TRANSLATE_NOOP("MainWindow", "Dinowrestler")},
	Archetype{0x11b, QT_TRANSLATE_NOOP("MainWindow", "Orcust")},
	Archetype{0x11c, QT_TRANSLATE_NOOP("MainWindow", "Thunder Dragon")},
	Archetype{0x11d, QT_TRANSLATE_NOOP("MainWindow", "Forbidden")},
	Archetype{0x11e, QT_TRANSLATE_NOOP("MainWindow", "Danger!")},
	Archetype{0x11f, QT_TRANSLATE_NOOP("MainWindow", "Nephthys")},
	Archetype{0x12, QT_TRANSLATE_NOOP("MainWindow", "Frog")},
	Archetype{0x120, QT_TRANSLATE_NOOP("MainWindow", "Prank-Kids")},
	Archetype{0x121, QT_TRANSLATE_NOOP("MainWindow", "Mayakashi")},
	Archetype{0x122, QT_TRANSLATE_NOOP("MainWindow", "Valkyrie")},
	Archetype{0x123, QT_TRANSLATE_NOOP("MainWindow", "Rose")},
	Archetype{0x124, QT_TRANSLATE_NOOP("MainWindow", "Machine Angel")},
	Archetype{0x125, QT_TRANSLATE_NOOP("MainWindow", "Smile")},
	Archetype{0x126, QT_TRANSLATE_NOOP("MainWindow", "Time Thief")},
	Archetype{0x127, QT_TRANSLATE_NOOP("MainWindow", "Infinitrack")},
	Archetype{0x128, QT_TRANSLATE_NOOP("MainWindow", "Witchcrafter")},
	Archetype{0x129, QT_TRANSLATE_NOOP("MainWindow", "Evil Eye")},
	Archetype{0x12a, QT_TRANSLATE_NOOP("MainWindow", "Endymion")},
	Archetype{0x12b, QT_TRANSLATE_NOOP("MainWindow", "Marincess")},
	Archetype{0x12c, QT_TRANSLATE_NOOP("MainWindow", "Tenyi")},
	Archetype{0x12d, QT_TRANSLATE_NOOP("MainWindow", "Simorgh")},
	Archetype{0x12e, QT_TRANSLATE_NOOP("MainWindow", "Fortune Fairy")},
	Archetype{0x12f, QT_TRANSLATE_NOOP("MainWindow", "Battlewasp")},
	Archetype{0x13, QT_TRANSLATE_NOOP("MainWindow", "Meklord")},
	Archetype{0x130, QT_TRANSLATE_NOOP("MainWindow", "Unchained")},
	Archetype{0x131, QT_TRANSLATE_NOOP("MainWindow", "Dream Mirror")},
	Archetype{0x132, QT_TRANSLATE_NOOP("MainWindow", "Mathmech")},
	Archetype{0x133, QT_TRANSLATE_NOOP("MainWindow", "Dragonmaid")},
	Archetype{0x134, QT_TRANSLATE_NOOP("MainWindow", "Generaider")},
	Archetype{0x135, QT_TRANSLATE_NOOP("MainWindow", "@Ignister")},
	Archetype{0x136, QT_TRANSLATE_NOOP("MainWindow", "A.I.")},
	Archetype{0x137, QT_TRANSLATE_NOOP("MainWindow", "Ancient Warriors")},
	Archetype{0x138, QT_TRANSLATE_NOOP("MainWindow", "Megalith")},
	Archetype{0x139, QT_TRANSLATE_NOOP("MainWindow", "Onomat")},
	Archetype{0x13a, QT_TRANSLATE_NOOP("MainWindow", "Palladium")},
	Archetype{0x13b, QT_TRANSLATE_NOOP("MainWindow", "Rebellion")},
	Archetype{0x13c, QT_TRANSLATE_NOOP("MainWindow", "Codebreaker")},
	Archetype{0x13d, QT_TRANSLATE_NOOP("MainWindow", "Nemeses")},
	Archetype{0x13e, QT_TRANSLATE_NOOP("MainWindow", "Barbaros")},
	Archetype{0x13f, QT_TRANSLATE_NOOP("MainWindow", "Plunder Patroll")},
	Archetype{0x14, QT_TRANSLATE_NOOP("MainWindow", "Allure Queen")},
	Archetype{0x140, QT_TRANSLATE_NOOP("MainWindow", "Adamancipator")},
	Archetype{0x141, QT_TRANSLATE_NOOP("MainWindow", "Rikka")},
	Archetype{0x142, QT_TRANSLATE_NOOP("MainWindow", "Eldlich")},
	Archetype{0x143, QT_TRANSLATE_NOOP("MainWindow", "Eldlixir")},
	Archetype{0x144, QT_TRANSLATE_NOOP("MainWindow", "Golden Land")},
	Archetype{0x145, QT_TRANSLATE_NOOP("MainWindow", "Phantasm")},
	Archetype{0x146, QT_TRANSLATE_NOOP("MainWindow", "Dogmatika")},
	Archetype{0x147, QT_TRANSLATE_NOOP("MainWindow", "Melffy")},
	Archetype{0x148, QT_TRANSLATE_NOOP("MainWindow", "Potan")},
	Archetype{0x149, QT_TRANSLATE_NOOP("MainWindow", "Roland")},
	Archetype{0x14a, QT_TRANSLATE_NOOP("MainWindow", "Appliancer")},
	Archetype{0x14b, QT_TRANSLATE_NOOP("MainWindow", "Numeron")},
	Archetype{0x14c, QT_TRANSLATE_NOOP("MainWindow", "Fossil")},
	Archetype{0x14d, QT_TRANSLATE_NOOP("MainWindow", "Spiritual Art")},
	Archetype{0x14e, QT_TRANSLATE_NOOP("MainWindow", "Dual Avatar")},
	Archetype{0x14f, QT_TRANSLATE_NOOP("MainWindow", "Tri-Brigade")},
	Archetype{0x15, QT_TRANSLATE_NOOP("MainWindow", "B.E.S.")},
	Archetype{0x150, QT_TRANSLATE_NOOP("MainWindow", "Virtual World")},
	Archetype{0x1509, QT_TRANSLATE_NOOP("MainWindow", "Barian's")},
	Archetype{0x150c, QT_TRANSLATE_NOOP("MainWindow", "Phantom Butterfly")},
	Archetype{0x150e, QT_TRANSLATE_NOOP("MainWindow", "Cat Girl")},
	Archetype{0x151, QT_TRANSLATE_NOOP("MainWindow", "Drytron")},
	Archetype{0x1512, QT_TRANSLATE_NOOP("MainWindow", "Royal Cookpal")},
	Archetype{0x1517, QT_TRANSLATE_NOOP("MainWindow", "Doll Monster")},
	Archetype{0x1518, QT_TRANSLATE_NOOP("MainWindow", "Doodle Beast")},
	Archetype{0x151a, QT_TRANSLATE_NOOP("MainWindow", "Earthbound")},
	Archetype{0x151b, QT_TRANSLATE_NOOP("MainWindow", "Magic Elf")},
	Archetype{0x152, QT_TRANSLATE_NOOP("MainWindow", "Magistus")},
	Archetype{0x1521, QT_TRANSLATE_NOOP("MainWindow", "Fossil Knight")},
	Archetype{0x1524, QT_TRANSLATE_NOOP("MainWindow", "Granel Attack")},
	Archetype{0x152c, QT_TRANSLATE_NOOP("MainWindow", "Jester Puppet")},
	Archetype{0x152f, QT_TRANSLATE_NOOP("MainWindow", "Champion")},
	Archetype{0x153, QT_TRANSLATE_NOOP("MainWindow", "Ki-sikil")},
	Archetype{0x1530, QT_TRANSLATE_NOOP("MainWindow", "Clock Knight")},
	Archetype{0x1538, QT_TRANSLATE_NOOP("MainWindow", "Stray Cat")},
	Archetype{0x154, QT_TRANSLATE_NOOP("MainWindow", "Lil-la")},
	Archetype{0x1541, QT_TRANSLATE_NOOP("MainWindow", "Quiz Panel")},
	Archetype{0x1549, QT_TRANSLATE_NOOP("MainWindow", "Skiel Attack")},
	Archetype{0x154a, QT_TRANSLATE_NOOP("MainWindow", "Angel")},
	Archetype{0x154d, QT_TRANSLATE_NOOP("MainWindow", "Spell Spice")},
	Archetype{0x154e, QT_TRANSLATE_NOOP("MainWindow", "Spirit Gem")},
	Archetype{0x155, QT_TRANSLATE_NOOP("MainWindow", "Evil★Twin")},
	Archetype{0x1550, QT_TRANSLATE_NOOP("MainWindow", "Pendulumstatue")},
	Archetype{0x1555, QT_TRANSLATE_NOOP("MainWindow", "Tachyon Dragon")},
	Archetype{0x155a, QT_TRANSLATE_NOOP("MainWindow", "\" V \"/\" V \"")},
	Archetype{0x155d, QT_TRANSLATE_NOOP("MainWindow", "White Knight")},
	Archetype{0x156, QT_TRANSLATE_NOOP("MainWindow", "Live☆Twin")},
	Archetype{0x1560, QT_TRANSLATE_NOOP("MainWindow", "Wisel Attack")},
	Archetype{0x157, QT_TRANSLATE_NOOP("MainWindow", "Sun")},
	Archetype{0x158, QT_TRANSLATE_NOOP("MainWindow", "Springans")},
	Archetype{0x159, QT_TRANSLATE_NOOP("MainWindow", "Myutant")},
	Archetype{0x15a, QT_TRANSLATE_NOOP("MainWindow", "S-Force")},
	Archetype{0x15b, QT_TRANSLATE_NOOP("MainWindow", "Starry Knight")},
	Archetype{0x15c, QT_TRANSLATE_NOOP("MainWindow", "Doll Monster")},
	Archetype{0x15d, QT_TRANSLATE_NOOP("MainWindow", "Rank-Down-Magic")},
	Archetype{0x15e, QT_TRANSLATE_NOOP("MainWindow", "Amazement")},
	Archetype{0x15f, QT_TRANSLATE_NOOP("MainWindow", "Attraction")},
	Archetype{0x16, QT_TRANSLATE_NOOP("MainWindow", "roid")},
	Archetype{0x160, QT_TRANSLATE_NOOP("MainWindow", "Branded")},
	Archetype{0x161, QT_TRANSLATE_NOOP("MainWindow", "War Rock")},
	Archetype{0x162, QT_TRANSLATE_NOOP("MainWindow", "Materiactor")},
	Archetype{0x163, QT_TRANSLATE_NOOP("MainWindow", "Ogdoadic")},
	Archetype{0x164, QT_TRANSLATE_NOOP("MainWindow", "Solfachord")},
	Archetype{0x165, QT_TRANSLATE_NOOP("MainWindow", "Ursarctic")},
	Archetype{0x166, QT_TRANSLATE_NOOP("MainWindow", "Despia")},
	Archetype{0x167, QT_TRANSLATE_NOOP("MainWindow", "Magikey")},
	Archetype{0x168, QT_TRANSLATE_NOOP("MainWindow", "Gunkan")},
	Archetype{0x169, QT_TRANSLATE_NOOP("MainWindow", "of the Forest")},
	Archetype{0x16a, QT_TRANSLATE_NOOP("MainWindow", "Stealth Kragen")},
	Archetype{0x16b, QT_TRANSLATE_NOOP("MainWindow", "Numerounius")},
	Archetype{0x16c, QT_TRANSLATE_NOOP("MainWindow", "Number")},
	Archetype{0x16d, QT_TRANSLATE_NOOP("MainWindow", "Swordsoul")},
	Archetype{0x16e, QT_TRANSLATE_NOOP("MainWindow", "Icejade")},
	Archetype{0x16f, QT_TRANSLATE_NOOP("MainWindow", "Floowandereeze")},
	Archetype{0x17, QT_TRANSLATE_NOOP("MainWindow", "Synchro")},
	Archetype{0x170, QT_TRANSLATE_NOOP("MainWindow", "Topologic")},
	Archetype{0x171, QT_TRANSLATE_NOOP("MainWindow", "Hyperion")},
	Archetype{0x172, QT_TRANSLATE_NOOP("MainWindow", "Beetrooper")},
	Archetype{0x173, QT_TRANSLATE_NOOP("MainWindow", "P.U.N.K.")},
	Archetype{0x174, QT_TRANSLATE_NOOP("MainWindow", "Exosister")},
	Archetype{0x174, QT_TRANSLATE_NOOP("MainWindow", "Exosister")},
	Archetype{0x175, QT_TRANSLATE_NOOP("MainWindow", "Dinomorphia")},
	Archetype{0x176, QT_TRANSLATE_NOOP("MainWindow", "Lady of Lament")},
	Archetype{0x177, QT_TRANSLATE_NOOP("MainWindow", "Seventh")},
	Archetype{0x178, QT_TRANSLATE_NOOP("MainWindow", "Barian")},
	Archetype{0x179, QT_TRANSLATE_NOOP("MainWindow", "Kairyu-Shin")},
	Archetype{0x17a, QT_TRANSLATE_NOOP("MainWindow", "Sea Stealth")},
	Archetype{0x17b, QT_TRANSLATE_NOOP("MainWindow", "Therion")},
	Archetype{0x17c, QT_TRANSLATE_NOOP("MainWindow", "Scareclaw")},
	Archetype{0x17d, QT_TRANSLATE_NOOP("MainWindow", "Libromancer")},
	Archetype{0x17e, QT_TRANSLATE_NOOP("MainWindow", "Vaylantz")},
	Archetype{0x17f, QT_TRANSLATE_NOOP("MainWindow", "Labrynth")},
	Archetype{0x18, QT_TRANSLATE_NOOP("MainWindow", "Cloudian")},
	Archetype{0x180, QT_TRANSLATE_NOOP("MainWindow", "Runick")},
	Archetype{0x181, QT_TRANSLATE_NOOP("MainWindow", "Spright")},
	Archetype{0x182, QT_TRANSLATE_NOOP("MainWindow", "Tearlaments")},
	Archetype{0x183, QT_TRANSLATE_NOOP("MainWindow", "Vernusylph")},
	Archetype{0x184, QT_TRANSLATE_NOOP("MainWindow", "Mokey Mokey")},
	Archetype{0x185, QT_TRANSLATE_NOOP("MainWindow", "Wingman")},
	Archetype{0x186, QT_TRANSLATE_NOOP("MainWindow", "Doodle")},
	Archetype{0x187, QT_TRANSLATE_NOOP("MainWindow", "G Golem")},
	Archetype{0x188, QT_TRANSLATE_NOOP("MainWindow", "Rainbow Bridge")},
	Archetype{0x189, QT_TRANSLATE_NOOP("MainWindow", "Byssted")},
	Archetype{0x189, QT_TRANSLATE_NOOP("MainWindow", "Bystial")},
	Archetype{0x18a, QT_TRANSLATE_NOOP("MainWindow", "Kashtira")},
	Archetype{0x18a, QT_TRANSLATE_NOOP("MainWindow", "Kshatri-La")},
	Archetype{0x18b, QT_TRANSLATE_NOOP("MainWindow", "Ghoti")},
	Archetype{0x18c, QT_TRANSLATE_NOOP("MainWindow", "Rescue-ACE")},
	Archetype{0x18d, QT_TRANSLATE_NOOP("MainWindow", "Purery")},
	Archetype{0x18d, QT_TRANSLATE_NOOP("MainWindow", "Purrely")},
	Archetype{0x18e, QT_TRANSLATE_NOOP("MainWindow", "Mikanko")},
	Archetype{0x18f, QT_TRANSLATE_NOOP("MainWindow", "Aquamirror")},
	Archetype{0x19, QT_TRANSLATE_NOOP("MainWindow", "Gladiator Beast")},
	Archetype{0x190, QT_TRANSLATE_NOOP("MainWindow", "Firewall")},
	Archetype{0x191, QT_TRANSLATE_NOOP("MainWindow", "Manadome")},
	Archetype{0x192, QT_TRANSLATE_NOOP("MainWindow", "Nemurelia")},
	Archetype{0x193, QT_TRANSLATE_NOOP("MainWindow", "Gold Pride")},
	Archetype{0x194, QT_TRANSLATE_NOOP("MainWindow", "Labyrinth Wall")},
	Archetype{0x195, QT_TRANSLATE_NOOP("MainWindow", "Favorite")},
	Archetype{0x196, QT_TRANSLATE_NOOP("MainWindow", "Vanquish Soul")},
	Archetype{0x197, QT_TRANSLATE_NOOP("MainWindow", "Nouvelles")},
	Archetype{0x198, QT_TRANSLATE_NOOP("MainWindow", "Recipe")},
	Archetype{0x1a, QT_TRANSLATE_NOOP("MainWindow", "Dark Scorpion")},
	Archetype{0x1b, QT_TRANSLATE_NOOP("MainWindow", "Phantom Beast")},
	Archetype{0x1c, QT_TRANSLATE_NOOP("MainWindow", "Spirit Message")},
	Archetype{0x1d, QT_TRANSLATE_NOOP("MainWindow", "Koa'ki Meiru")},
	Archetype{0x1e, QT_TRANSLATE_NOOP("MainWindow", "Chrysalis")},
	Archetype{0x1f, QT_TRANSLATE_NOOP("MainWindow", "Neo-Spacian")},
	Archetype{0x2, QT_TRANSLATE_NOOP("MainWindow", "Genex")},
	Archetype{0x20, QT_TRANSLATE_NOOP("MainWindow", "Shien")},
	Archetype{0x2002, QT_TRANSLATE_NOOP("MainWindow", "Genex Ally")},
	Archetype{0x2016, QT_TRANSLATE_NOOP("MainWindow", "Speedroid")},
	Archetype{0x2017, QT_TRANSLATE_NOOP("MainWindow", "Synchro Dragon")},
	Archetype{0x2033, QT_TRANSLATE_NOOP("MainWindow", "Blackwing Tamer")},
	Archetype{0x2034, QT_TRANSLATE_NOOP("MainWindow", "Ultimate Crystal")},
	Archetype{0x2048, QT_TRANSLATE_NOOP("MainWindow", "Number S")},
	Archetype{0x2066, QT_TRANSLATE_NOOP("MainWindow", "Magnet Warrior")},
	Archetype{0x206f, QT_TRANSLATE_NOOP("MainWindow", "Heroic Champion")},
	Archetype{0x2073, QT_TRANSLATE_NOOP("MainWindow", "Xyz Dragon")},
	Archetype{0x207a, QT_TRANSLATE_NOOP("MainWindow", "Noble Arms")},
	Archetype{0x207e, QT_TRANSLATE_NOOP("MainWindow", "ZS -")},
	Archetype{0x207f, QT_TRANSLATE_NOOP("MainWindow", "Utopic Future")},
	Archetype{0x2093, QT_TRANSLATE_NOOP("MainWindow", "Cyber Angel")},
	Archetype{0x209b, QT_TRANSLATE_NOOP("MainWindow", "Melodious Songstress")},
	Archetype{0x20a2, QT_TRANSLATE_NOOP("MainWindow", "Magician Girl")},
	Archetype{0x20b5, QT_TRANSLATE_NOOP("MainWindow", "Spiritual Beast")},
	Archetype{0x20b7, QT_TRANSLATE_NOOP("MainWindow", "Elder Entity")},
	Archetype{0x20cd, QT_TRANSLATE_NOOP("MainWindow", "Aquarium")},
	Archetype{0x20dc, QT_TRANSLATE_NOOP("MainWindow", "Super Quantal Mech Beast")},
	Archetype{0x20ec, QT_TRANSLATE_NOOP("MainWindow", "Abyss Script")},
	Archetype{0x20ee, QT_TRANSLATE_NOOP("MainWindow", "SPYRAL MISSION")},
	Archetype{0x20f2, QT_TRANSLATE_NOOP("MainWindow", "Pendulumgraph")},
	Archetype{0x20f8, QT_TRANSLATE_NOOP("MainWindow", "Supreme King Dragon")},
	Archetype{0x21, QT_TRANSLATE_NOOP("MainWindow", "Earthbound Immortal")},
	Archetype{0x2157, QT_TRANSLATE_NOOP("MainWindow", "Sunvine")},
	Archetype{0x2169, QT_TRANSLATE_NOOP("MainWindow", "Mystical Spirit of the Forest")},
	Archetype{0x2178, QT_TRANSLATE_NOOP("MainWindow", "Battleguard")},
	Archetype{0x2186, QT_TRANSLATE_NOOP("MainWindow", "Doodlebook")},
	Archetype{0x22, QT_TRANSLATE_NOOP("MainWindow", "Jurrac")},
	Archetype{0x23, QT_TRANSLATE_NOOP("MainWindow", "Malefic")},
	Archetype{0x24, QT_TRANSLATE_NOOP("MainWindow", "Scrap")},
	Archetype{0x25, QT_TRANSLATE_NOOP("MainWindow", "Iron Chain")},
	Archetype{0x2509, QT_TRANSLATE_NOOP("MainWindow", "Battleguard")},
	Archetype{0x2517, QT_TRANSLATE_NOOP("MainWindow", "Doll Part")},
	Archetype{0x2521, QT_TRANSLATE_NOOP("MainWindow", "Cenozoic")},
	Archetype{0x2524, QT_TRANSLATE_NOOP("MainWindow", "Granel Guard")},
	Archetype{0x2549, QT_TRANSLATE_NOOP("MainWindow", "Skiel Guard")},
	Archetype{0x254a, QT_TRANSLATE_NOOP("MainWindow", "Celestial")},
	Archetype{0x2560, QT_TRANSLATE_NOOP("MainWindow", "Wisel Guard")},
	Archetype{0x26, QT_TRANSLATE_NOOP("MainWindow", "Morphtronic")},
	Archetype{0x27, QT_TRANSLATE_NOOP("MainWindow", "T.G.")},
	Archetype{0x28, QT_TRANSLATE_NOOP("MainWindow", "Batteryman")},
	Archetype{0x29, QT_TRANSLATE_NOOP("MainWindow", "Dragunity")},
	Archetype{0x293, QT_TRANSLATE_NOOP("MainWindow", "Visas")},
	Archetype{0x294, QT_TRANSLATE_NOOP("MainWindow", "Counter")},
	Archetype{0x295, QT_TRANSLATE_NOOP("MainWindow", "Battlin' Boxing")},
	Archetype{0x2a, QT_TRANSLATE_NOOP("MainWindow", "Naturia")},
	Archetype{0x2b, QT_TRANSLATE_NOOP("MainWindow", "Ninja")},
	Archetype{0x2c, QT_TRANSLATE_NOOP("MainWindow", "Flamvell")},
	Archetype{0x2d, QT_TRANSLATE_NOOP("MainWindow", "Nitro")},
	Archetype{0x2e, QT_TRANSLATE_NOOP("MainWindow", "Gravekeeper's")},
	Archetype{0x2f, QT_TRANSLATE_NOOP("MainWindow", "Ice Barrier")},
	Archetype{0x3, QT_TRANSLATE_NOOP("MainWindow", "Horus the Black Flame Dragon")},
	Archetype{0x30, QT_TRANSLATE_NOOP("MainWindow", "Vylon")},
	Archetype{0x3008, QT_TRANSLATE_NOOP("MainWindow", "Elemental HERO")},
	Archetype{0x300d, QT_TRANSLATE_NOOP("MainWindow", "XX-Saber")},
	Archetype{0x3013, QT_TRANSLATE_NOOP("MainWindow", "Meklord Emperor")},
	Archetype{0x3042, QT_TRANSLATE_NOOP("MainWindow", "Nordic Ascendant")},
	Archetype{0x304e, QT_TRANSLATE_NOOP("MainWindow", "Evoltile")},
	Archetype{0x307b, QT_TRANSLATE_NOOP("MainWindow", "Galaxy-Eyes Tachyon Dragon")},
	Archetype{0x30a2, QT_TRANSLATE_NOOP("MainWindow", "Dark Magician Girl")},
	Archetype{0x30b5, QT_TRANSLATE_NOOP("MainWindow", "Spiritual Beast Tamer")},
	Archetype{0x31, QT_TRANSLATE_NOOP("MainWindow", "Fortune Lady")},
	Archetype{0x314d, QT_TRANSLATE_NOOP("MainWindow", "Spiritual Earth Art")},
	Archetype{0x316, QT_TRANSLATE_NOOP("MainWindow", "Darkness")},
	Archetype{0x32, QT_TRANSLATE_NOOP("MainWindow", "Volcanic")},
	Archetype{0x33, QT_TRANSLATE_NOOP("MainWindow", "Blackwing")},
	Archetype{0x34, QT_TRANSLATE_NOOP("MainWindow", "Crystal")},
	Archetype{0x35, QT_TRANSLATE_NOOP("MainWindow", "Fabled")},
	Archetype{0x351a, QT_TRANSLATE_NOOP("MainWindow", "Earthbound Servant")},
	Archetype{0x3521, QT_TRANSLATE_NOOP("MainWindow", "Cenozoic Fossil Knight")},
	Archetype{0x36, QT_TRANSLATE_NOOP("MainWindow", "Machina")},
	Archetype{0x37, QT_TRANSLATE_NOOP("MainWindow", "Mist Valley")},
	Archetype{0x38, QT_TRANSLATE_NOOP("MainWindow", "Lightsworn")},
	Archetype{0x39, QT_TRANSLATE_NOOP("MainWindow", "Laval")},
	Archetype{0x3a, QT_TRANSLATE_NOOP("MainWindow", "Gishki")},
	Archetype{0x3b, QT_TRANSLATE_NOOP("MainWindow", "Red-Eyes")},
	Archetype{0x3c, QT_TRANSLATE_NOOP("MainWindow", "Reptilianne")},
	Archetype{0x3d, QT_TRANSLATE_NOOP("MainWindow", "Six Samurai")},
	Archetype{0x3e, QT_TRANSLATE_NOOP("MainWindow", "Worm")},
	Archetype{0x3f, QT_TRANSLATE_NOOP("MainWindow", "Majestic")},
	Archetype{0x4, QT_TRANSLATE_NOOP("MainWindow", "Amazoness")},
	Archetype{0x40, QT_TRANSLATE_NOOP("MainWindow", "Forbidden One")},
	Archetype{0x400d, QT_TRANSLATE_NOOP("MainWindow", "Elementsaber")},
	Archetype{0x407a, QT_TRANSLATE_NOOP("MainWindow", "Infernoble")},
	Archetype{0x4093, QT_TRANSLATE_NOOP("MainWindow", "Cyberdark")},
	Archetype{0x40b5, QT_TRANSLATE_NOOP("MainWindow", "Ritual Beast Ulti-")},
	Archetype{0x40b7, QT_TRANSLATE_NOOP("MainWindow", "Old Entity")},
	Archetype{0x40ec, QT_TRANSLATE_NOOP("MainWindow", "Abyss Costume")},
	Archetype{0x41, QT_TRANSLATE_NOOP("MainWindow", "LV")},
	Archetype{0x4157, QT_TRANSLATE_NOOP("MainWindow", "Sunseed")},
	Archetype{0x42, QT_TRANSLATE_NOOP("MainWindow", "Nordic")},
	Archetype{0x43, QT_TRANSLATE_NOOP("MainWindow", "Junk")},
	Archetype{0x44, QT_TRANSLATE_NOOP("MainWindow", "The Agent")},
	Archetype{0x45, QT_TRANSLATE_NOOP("MainWindow", "Archfiend")},
	Archetype{0x4521, QT_TRANSLATE_NOOP("MainWindow", "Mezozoic")},
	Archetype{0x4524, QT_TRANSLATE_NOOP("MainWindow", "Granel Top")},
	Archetype{0x4549, QT_TRANSLATE_NOOP("MainWindow", "Skiel Top")},
	Archetype{0x4560, QT_TRANSLATE_NOOP("MainWindow", "Wisel Top")},
	Archetype{0x46, QT_TRANSLATE_NOOP("MainWindow", "Polymerization|Fusion")},
	Archetype{0x47, QT_TRANSLATE_NOOP("MainWindow", "Gem-")},
	Archetype{0x48, QT_TRANSLATE_NOOP("MainWindow", "Number")},
	Archetype{0x49, QT_TRANSLATE_NOOP("MainWindow", "Skyblaster")},
	Archetype{0x4a, QT_TRANSLATE_NOOP("MainWindow", "Timelord")},
	Archetype{0x4b, QT_TRANSLATE_NOOP("MainWindow", "Aesir")},
	Archetype{0x4c, QT_TRANSLATE_NOOP("MainWindow", "Trap Hole")},
	Archetype{0x4d, QT_TRANSLATE_NOOP("MainWindow", "Beast's Battle")},
	Archetype{0x4e, QT_TRANSLATE_NOOP("MainWindow", "Evol")},
	Archetype{0x4f, QT_TRANSLATE_NOOP("MainWindow", "Dark Lucius")},
	Archetype{0x5, QT_TRANSLATE_NOOP("MainWindow", "Arcana Force")},
	Archetype{0x50, QT_TRANSLATE_NOOP("MainWindow", "Venom")},
	Archetype{0x500, QT_TRANSLATE_NOOP("MainWindow", "Speed Spell")},
	Archetype{0x5008, QT_TRANSLATE_NOOP("MainWindow", "Vision HERO")},
	Archetype{0x501, QT_TRANSLATE_NOOP("MainWindow", "Alchemy Beast")},
	Archetype{0x502, QT_TRANSLATE_NOOP("MainWindow", "Alligator")},
	Archetype{0x503, QT_TRANSLATE_NOOP("MainWindow", "Anti")},
	Archetype{0x5034, QT_TRANSLATE_NOOP("MainWindow", "Advanced Crystal Beast")},
	Archetype{0x504, QT_TRANSLATE_NOOP("MainWindow", "Assassin")},
	Archetype{0x5042, QT_TRANSLATE_NOOP("MainWindow", "Nordic Relic")},
	Archetype{0x5048, QT_TRANSLATE_NOOP("MainWindow", "Number C39")},
	Archetype{0x504e, QT_TRANSLATE_NOOP("MainWindow", "Evolzar")},
	Archetype{0x505, QT_TRANSLATE_NOOP("MainWindow", "Astral")},
	Archetype{0x506, QT_TRANSLATE_NOOP("MainWindow", "Atlandis")},
	Archetype{0x507, QT_TRANSLATE_NOOP("MainWindow", "Attack")},
	Archetype{0x507a, QT_TRANSLATE_NOOP("MainWindow", "Infernoble Knight")},
	Archetype{0x508, QT_TRANSLATE_NOOP("MainWindow", "Baby")},
	Archetype{0x509, QT_TRANSLATE_NOOP("MainWindow", "Barian")},
	Archetype{0x50b, QT_TRANSLATE_NOOP("MainWindow", "Beastborg")},
	Archetype{0x50c, QT_TRANSLATE_NOOP("MainWindow", "Butterfly")},
	Archetype{0x50d, QT_TRANSLATE_NOOP("MainWindow", "Carrier")},
	Archetype{0x50e, QT_TRANSLATE_NOOP("MainWindow", "Cat")},
	Archetype{0x50f, QT_TRANSLATE_NOOP("MainWindow", "Cicada")},
	Archetype{0x51, QT_TRANSLATE_NOOP("MainWindow", "Gadget")},
	Archetype{0x510, QT_TRANSLATE_NOOP("MainWindow", "Clear")},
	Archetype{0x511, QT_TRANSLATE_NOOP("MainWindow", "Comics Hero")},
	Archetype{0x512, QT_TRANSLATE_NOOP("MainWindow", "Cookpal")},
	Archetype{0x513, QT_TRANSLATE_NOOP("MainWindow", "Dart")},
	Archetype{0x514, QT_TRANSLATE_NOOP("MainWindow", "Dice")},
	Archetype{0x514d, QT_TRANSLATE_NOOP("MainWindow", "Spiritual Fire Art")},
	Archetype{0x515, QT_TRANSLATE_NOOP("MainWindow", "Dizzy")},
	Archetype{0x516, QT_TRANSLATE_NOOP("MainWindow", "Dog")},
	Archetype{0x517, QT_TRANSLATE_NOOP("MainWindow", "Doll")},
	Archetype{0x518, QT_TRANSLATE_NOOP("MainWindow", "Doodle")},
	Archetype{0x519, QT_TRANSLATE_NOOP("MainWindow", "Dyson")},
	Archetype{0x51a, QT_TRANSLATE_NOOP("MainWindow", "Earth")},
	Archetype{0x51b, QT_TRANSLATE_NOOP("MainWindow", "Elf")},
	Archetype{0x51d, QT_TRANSLATE_NOOP("MainWindow", "Fairy")},
	Archetype{0x51e, QT_TRANSLATE_NOOP("MainWindow", "Forbidden Beast")},
	Archetype{0x51f, QT_TRANSLATE_NOOP("MainWindow", "Forest")},
	Archetype{0x52, QT_TRANSLATE_NOOP("MainWindow", "Guardian")},
	Archetype{0x520, QT_TRANSLATE_NOOP("MainWindow", "Fortune Fairy")},
	Archetype{0x521, QT_TRANSLATE_NOOP("MainWindow", "Gaia the Dragon Champion")},
	Archetype{0x522, QT_TRANSLATE_NOOP("MainWindow", "Gorgonic")},
	Archetype{0x523, QT_TRANSLATE_NOOP("MainWindow", "Goyo")},
	Archetype{0x524, QT_TRANSLATE_NOOP("MainWindow", "Granel")},
	Archetype{0x525, QT_TRANSLATE_NOOP("MainWindow", "Guard")},
	Archetype{0x526, QT_TRANSLATE_NOOP("MainWindow", "Guts Master")},
	Archetype{0x527, QT_TRANSLATE_NOOP("MainWindow", "Hand")},
	Archetype{0x528, QT_TRANSLATE_NOOP("MainWindow", "Heart Monster")},
	Archetype{0x529, QT_TRANSLATE_NOOP("MainWindow", "Heavy Industry")},
	Archetype{0x52a, QT_TRANSLATE_NOOP("MainWindow", "Inu")},
	Archetype{0x52b, QT_TRANSLATE_NOOP("MainWindow", "Ivy")},
	Archetype{0x52c, QT_TRANSLATE_NOOP("MainWindow", "Jester")},
	Archetype{0x52d, QT_TRANSLATE_NOOP("MainWindow", "Jutte")},
	Archetype{0x52e, QT_TRANSLATE_NOOP("MainWindow", "Kabuki Stage")},
	Archetype{0x52f, QT_TRANSLATE_NOOP("MainWindow", "King")},
	Archetype{0x53, QT_TRANSLATE_NOOP("MainWindow", "Constellar")},
	Archetype{0x530, QT_TRANSLATE_NOOP("MainWindow", "Knight")},
	Archetype{0x531, QT_TRANSLATE_NOOP("MainWindow", "Koala")},
	Archetype{0x533, QT_TRANSLATE_NOOP("MainWindow", "Landstar")},
	Archetype{0x534, QT_TRANSLATE_NOOP("MainWindow", "Magnet")},
	Archetype{0x535, QT_TRANSLATE_NOOP("MainWindow", "Mantis")},
	Archetype{0x536, QT_TRANSLATE_NOOP("MainWindow", "Mosquito")},
	Archetype{0x537, QT_TRANSLATE_NOOP("MainWindow", "Motor")},
	Archetype{0x538, QT_TRANSLATE_NOOP("MainWindow", "Neko")},
	Archetype{0x53b, QT_TRANSLATE_NOOP("MainWindow", "Numeronius")},
	Archetype{0x53c, QT_TRANSLATE_NOOP("MainWindow", "Papillon")},
	Archetype{0x53d, QT_TRANSLATE_NOOP("MainWindow", "Parasite")},
	Archetype{0x53e, QT_TRANSLATE_NOOP("MainWindow", "Pixie")},
	Archetype{0x53f, QT_TRANSLATE_NOOP("MainWindow", "Priestess")},
	Archetype{0x54, QT_TRANSLATE_NOOP("MainWindow", "Gagaga")},
	Archetype{0x540, QT_TRANSLATE_NOOP("MainWindow", "Puppet")},
	Archetype{0x541, QT_TRANSLATE_NOOP("MainWindow", "Quiz")},
	Archetype{0x542, QT_TRANSLATE_NOOP("MainWindow", "Raccoon")},
	Archetype{0x543, QT_TRANSLATE_NOOP("MainWindow", "Red")},
	Archetype{0x545, QT_TRANSLATE_NOOP("MainWindow", "Seal")},
	Archetype{0x546, QT_TRANSLATE_NOOP("MainWindow", "Shaman")},
	Archetype{0x547, QT_TRANSLATE_NOOP("MainWindow", "Shark")},
	Archetype{0x548, QT_TRANSLATE_NOOP("MainWindow", "Shining")},
	Archetype{0x549, QT_TRANSLATE_NOOP("MainWindow", "Skiel")},
	Archetype{0x54a, QT_TRANSLATE_NOOP("MainWindow", "Sky")},
	Archetype{0x54b, QT_TRANSLATE_NOOP("MainWindow", "Slime")},
	Archetype{0x54c, QT_TRANSLATE_NOOP("MainWindow", "Sphere")},
	Archetype{0x54d, QT_TRANSLATE_NOOP("MainWindow", "Spice")},
	Archetype{0x54e, QT_TRANSLATE_NOOP("MainWindow", "Spirit")},
	Archetype{0x54f, QT_TRANSLATE_NOOP("MainWindow", "Starship")},
	Archetype{0x55, QT_TRANSLATE_NOOP("MainWindow", "Photon")},
	Archetype{0x550, QT_TRANSLATE_NOOP("MainWindow", "Statue")},
	Archetype{0x551, QT_TRANSLATE_NOOP("MainWindow", "Stone")},
	Archetype{0x552, QT_TRANSLATE_NOOP("MainWindow", "Strain")},
	Archetype{0x5521, QT_TRANSLATE_NOOP("MainWindow", "Mezozoic Fossil Knight")},
	Archetype{0x555, QT_TRANSLATE_NOOP("MainWindow", "Tachyon")},
	Archetype{0x556, QT_TRANSLATE_NOOP("MainWindow", "Thorn Prisoner")},
	Archetype{0x557, QT_TRANSLATE_NOOP("MainWindow", "Top")},
	Archetype{0x558, QT_TRANSLATE_NOOP("MainWindow", "Toy (Arc-V)")},
	Archetype{0x559, QT_TRANSLATE_NOOP("MainWindow", "Toy")},
	Archetype{0x55a, QT_TRANSLATE_NOOP("MainWindow", "V")},
	Archetype{0x55c, QT_TRANSLATE_NOOP("MainWindow", "Vigilante")},
	Archetype{0x55d, QT_TRANSLATE_NOOP("MainWindow", "White")},
	Archetype{0x55f, QT_TRANSLATE_NOOP("MainWindow", "Sinister Doctrine")},
	Archetype{0x56, QT_TRANSLATE_NOOP("MainWindow", "Inzektor")},
	Archetype{0x560, QT_TRANSLATE_NOOP("MainWindow", "Wisel")},
	Archetype{0x561, QT_TRANSLATE_NOOP("MainWindow", "Yubel")},
	Archetype{0x562, QT_TRANSLATE_NOOP("MainWindow", "∞")},
	Archetype{0x563, QT_TRANSLATE_NOOP("MainWindow", "Yomi")},
	Archetype{0x564, QT_TRANSLATE_NOOP("MainWindow", "Shogi|Line Monster")},
	Archetype{0x565, QT_TRANSLATE_NOOP("MainWindow", "Hunder")},
	Archetype{0x566, QT_TRANSLATE_NOOP("MainWindow", "Heraldic")},
	Archetype{0x567, QT_TRANSLATE_NOOP("MainWindow", "Hell")},
	Archetype{0x568, QT_TRANSLATE_NOOP("MainWindow", "C")},
	Archetype{0x569, QT_TRANSLATE_NOOP("MainWindow", "Eco Spell")},
	Archetype{0x56a, QT_TRANSLATE_NOOP("MainWindow", "Junk Robot")},
	Archetype{0x56b, QT_TRANSLATE_NOOP("MainWindow", "W")},
	Archetype{0x56c, QT_TRANSLATE_NOOP("MainWindow", "X")},
	Archetype{0x56d, QT_TRANSLATE_NOOP("MainWindow", "Y")},
	Archetype{0x56e, QT_TRANSLATE_NOOP("MainWindow", "Z")},
	Archetype{0x56f, QT_TRANSLATE_NOOP("MainWindow", "Dark Mummy")},
	Archetype{0x57, QT_TRANSLATE_NOOP("MainWindow", "Resonator")},
	Archetype{0x570, QT_TRANSLATE_NOOP("MainWindow", "Tentacluster")},
	Archetype{0x571, QT_TRANSLATE_NOOP("MainWindow", "Monarch (monster)")},
	Archetype{0x572, QT_TRANSLATE_NOOP("MainWindow", "Mirror Imagine")},
	Archetype{0x573, QT_TRANSLATE_NOOP("MainWindow", "Helixx")},
	Archetype{0x574, QT_TRANSLATE_NOOP("MainWindow", "Sunavalon")},
	Archetype{0x575, QT_TRANSLATE_NOOP("MainWindow", "Sunvine")},
	Archetype{0x576, QT_TRANSLATE_NOOP("MainWindow", "Starving Venemy")},
	Archetype{0x577, QT_TRANSLATE_NOOP("MainWindow", "Hydradrive")},
	Archetype{0x578, QT_TRANSLATE_NOOP("MainWindow", "Armatos Legio")},
	Archetype{0x579, QT_TRANSLATE_NOOP("MainWindow", "D-Scale")},
	Archetype{0x57a, QT_TRANSLATE_NOOP("MainWindow", "Appliancer")},
	Archetype{0x57b, QT_TRANSLATE_NOOP("MainWindow", "Topologina")},
	Archetype{0x58, QT_TRANSLATE_NOOP("MainWindow", "Wind-Up")},
	Archetype{0x580, QT_TRANSLATE_NOOP("MainWindow", "Stormrider")},
	Archetype{0x581, QT_TRANSLATE_NOOP("MainWindow", "Drone")},
	Archetype{0x583, QT_TRANSLATE_NOOP("MainWindow", "Mask")},
	Archetype{0x59, QT_TRANSLATE_NOOP("MainWindow", "Gogogo")},
	Archetype{0x5a, QT_TRANSLATE_NOOP("MainWindow", "Penguin")},
	Archetype{0x5b, QT_TRANSLATE_NOOP("MainWindow", "Inmato")},
	Archetype{0x5c, QT_TRANSLATE_NOOP("MainWindow", "Sphinx")},
	Archetype{0x5d, QT_TRANSLATE_NOOP("MainWindow", "Ultimate Insect")},
	Archetype{0x5e, QT_TRANSLATE_NOOP("MainWindow", "Dark Mimic")},
	Archetype{0x5f, QT_TRANSLATE_NOOP("MainWindow", "Mystic Swordsman")},
	Archetype{0x6, QT_TRANSLATE_NOOP("MainWindow", "Dark World")},
	Archetype{0x60, QT_TRANSLATE_NOOP("MainWindow", "Bamboo Sword")},
	Archetype{0x600, QT_TRANSLATE_NOOP("MainWindow", "Dark Tuner")},
	Archetype{0x6008, QT_TRANSLATE_NOOP("MainWindow", "Evil HERO")},
	Archetype{0x601, QT_TRANSLATE_NOOP("MainWindow", "Dark Synchro")},
	Archetype{0x6013, QT_TRANSLATE_NOOP("MainWindow", "Meklord Army")},
	Archetype{0x6042, QT_TRANSLATE_NOOP("MainWindow", "Nordic Beast")},
	Archetype{0x604e, QT_TRANSLATE_NOOP("MainWindow", "Evolsaur")},
	Archetype{0x607a, QT_TRANSLATE_NOOP("MainWindow", "Infernoble Arms")},
	Archetype{0x61, QT_TRANSLATE_NOOP("MainWindow", "Ninjitsu Art")},
	Archetype{0x614d, QT_TRANSLATE_NOOP("MainWindow", "Spiritual Water Art")},
	Archetype{0x62, QT_TRANSLATE_NOOP("MainWindow", "Toon")},
	Archetype{0x63, QT_TRANSLATE_NOOP("MainWindow", "Reactor")},
	Archetype{0x64, QT_TRANSLATE_NOOP("MainWindow", "Harpie")},
	Archetype{0x65, QT_TRANSLATE_NOOP("MainWindow", "Infestation")},
	Archetype{0x66, QT_TRANSLATE_NOOP("MainWindow", "Warrior")},
	Archetype{0x67, QT_TRANSLATE_NOOP("MainWindow", "Iron")},
	Archetype{0x67, QT_TRANSLATE_NOOP("MainWindow", "Koala")},
	Archetype{0x68, QT_TRANSLATE_NOOP("MainWindow", "Kangaroo")},
	Archetype{0x68, QT_TRANSLATE_NOOP("MainWindow", "Tin")},
	Archetype{0x69, QT_TRANSLATE_NOOP("MainWindow", "Hieratic")},
	Archetype{0x6a, QT_TRANSLATE_NOOP("MainWindow", "Butterspy")},
	Archetype{0x6b, QT_TRANSLATE_NOOP("MainWindow", "Bounzer")},
	Archetype{0x6c, QT_TRANSLATE_NOOP("MainWindow", "Lightray")},
	Archetype{0x6d, QT_TRANSLATE_NOOP("MainWindow", "Djinn")},
	Archetype{0x6e, QT_TRANSLATE_NOOP("MainWindow", "Prophecy")},
	Archetype{0x6f, QT_TRANSLATE_NOOP("MainWindow", "Heroic")},
	Archetype{0x7, QT_TRANSLATE_NOOP("MainWindow", "Ancient Gear")},
	Archetype{0x70, QT_TRANSLATE_NOOP("MainWindow", "Chronomaly")},
	Archetype{0x71, QT_TRANSLATE_NOOP("MainWindow", "Madolche")},
	Archetype{0x72, QT_TRANSLATE_NOOP("MainWindow", "Geargia")},
	Archetype{0x73, QT_TRANSLATE_NOOP("MainWindow", "Xyz")},
	Archetype{0x74, QT_TRANSLATE_NOOP("MainWindow", "Mermail")},
	Archetype{0x75, QT_TRANSLATE_NOOP("MainWindow", "Abyss-")},
	Archetype{0x76, QT_TRANSLATE_NOOP("MainWindow", "Heraldic Beast")},
	Archetype{0x77, QT_TRANSLATE_NOOP("MainWindow", "Atlantean")},
	Archetype{0x78, QT_TRANSLATE_NOOP("MainWindow", "Nimble")},
	Archetype{0x79, QT_TRANSLATE_NOOP("MainWindow", "Fire Fist")},
	Archetype{0x7a, QT_TRANSLATE_NOOP("MainWindow", "Noble")},
	Archetype{0x7b, QT_TRANSLATE_NOOP("MainWindow", "Galaxy")},
	Archetype{0x7c, QT_TRANSLATE_NOOP("MainWindow", "Fire Formation")},
	Archetype{0x7d, QT_TRANSLATE_NOOP("MainWindow", "Hazy")},
	Archetype{0x7e, QT_TRANSLATE_NOOP("MainWindow", "Zexal")},
	Archetype{0x7f, QT_TRANSLATE_NOOP("MainWindow", "Utopic")},
	Archetype{0x8, QT_TRANSLATE_NOOP("MainWindow", "HERO")},
	Archetype{0x80, QT_TRANSLATE_NOOP("MainWindow", "Duston")},
	Archetype{0x81, QT_TRANSLATE_NOOP("MainWindow", "Fire King")},
	Archetype{0x82, QT_TRANSLATE_NOOP("MainWindow", "Dododo")},
	Archetype{0x83, QT_TRANSLATE_NOOP("MainWindow", "Puppet")},
	Archetype{0x84, QT_TRANSLATE_NOOP("MainWindow", "Battlin' Boxer")},
	Archetype{0x85, QT_TRANSLATE_NOOP("MainWindow", "Super Defense Robot")},
	Archetype{0x8521, QT_TRANSLATE_NOOP("MainWindow", "Paleozoic")},
	Archetype{0x8524, QT_TRANSLATE_NOOP("MainWindow", "Granel Carrier")},
	Archetype{0x8549, QT_TRANSLATE_NOOP("MainWindow", "Skiel Carrier")},
	Archetype{0x8560, QT_TRANSLATE_NOOP("MainWindow", "Wisel Carrier")},
	Archetype{0x86, QT_TRANSLATE_NOOP("MainWindow", "Star Seraph")},
	Archetype{0x87, QT_TRANSLATE_NOOP("MainWindow", "Umbral Horror")},
	Archetype{0x88, QT_TRANSLATE_NOOP("MainWindow", "Bujin")},
	Archetype{0x89, QT_TRANSLATE_NOOP("MainWindow", "Hole")},
	Archetype{0x8a, QT_TRANSLATE_NOOP("MainWindow", "Envy")},
	Archetype{0x8b, QT_TRANSLATE_NOOP("MainWindow", "Malicevorous")},
	Archetype{0x8c, QT_TRANSLATE_NOOP("MainWindow", "Druid")},
	Archetype{0x8d, QT_TRANSLATE_NOOP("MainWindow", "Ghostrick")},
	Archetype{0x8e, QT_TRANSLATE_NOOP("MainWindow", "Vampire")},
	Archetype{0x8f, QT_TRANSLATE_NOOP("MainWindow", "Zubaba")},
	Archetype{0x9, QT_TRANSLATE_NOOP("MainWindow", "Neos")},
	Archetype{0x90, QT_TRANSLATE_NOOP("MainWindow", "Sylvan")},
	Archetype{0x9013, QT_TRANSLATE_NOOP("MainWindow", "Meklord Astro")},
	Archetype{0x91, QT_TRANSLATE_NOOP("MainWindow", "Necrovalley")},
	Archetype{0x92, QT_TRANSLATE_NOOP("MainWindow", "Heraldry")},
	Archetype{0x93, QT_TRANSLATE_NOOP("MainWindow", "Cyber")},
	Archetype{0x94, QT_TRANSLATE_NOOP("MainWindow", "Cybernetic")},
	Archetype{0x95, QT_TRANSLATE_NOOP("MainWindow", "Rank-Up-Magic")},
	Archetype{0x9521, QT_TRANSLATE_NOOP("MainWindow", "Paleozoic Fossil Knight")},
	Archetype{0x96, QT_TRANSLATE_NOOP("MainWindow", "Fishborg")},
	Archetype{0x97, QT_TRANSLATE_NOOP("MainWindow", "Artifact")},
	Archetype{0x98, QT_TRANSLATE_NOOP("MainWindow", "Magician")},
	Archetype{0x99, QT_TRANSLATE_NOOP("MainWindow", "Odd-Eyes")},
	Archetype{0x9a, QT_TRANSLATE_NOOP("MainWindow", "Superheavy Samurai")},
	Archetype{0x9b, QT_TRANSLATE_NOOP("MainWindow", "Melodious")},
	Archetype{0x9c, QT_TRANSLATE_NOOP("MainWindow", "tellarknight")},
	Archetype{0x9d, QT_TRANSLATE_NOOP("MainWindow", "Shaddoll")},
	Archetype{0x9e, QT_TRANSLATE_NOOP("MainWindow", "Yang Zing")},
	Archetype{0x9f, QT_TRANSLATE_NOOP("MainWindow", "Performapal")},
	Archetype{0xa, QT_TRANSLATE_NOOP("MainWindow", "lswarm")},
	Archetype{0xa0, QT_TRANSLATE_NOOP("MainWindow", "Legendary Knight")},
	Archetype{0xa008, QT_TRANSLATE_NOOP("MainWindow", "Masked HERO")},
	Archetype{0xa042, QT_TRANSLATE_NOOP("MainWindow", "Nordic Alfar")},
	Archetype{0xa1, QT_TRANSLATE_NOOP("MainWindow", "Legendary Dragon")},
	Archetype{0xa14d, QT_TRANSLATE_NOOP("MainWindow", "Spiritual Wind Art")},
	Archetype{0xa2, QT_TRANSLATE_NOOP("MainWindow", "Magician")},
	Archetype{0xa3, QT_TRANSLATE_NOOP("MainWindow", "Stardust")},
	Archetype{0xa4, QT_TRANSLATE_NOOP("MainWindow", "Kuriboh")},
	Archetype{0xa5, QT_TRANSLATE_NOOP("MainWindow", "Change")},
	Archetype{0xa6, QT_TRANSLATE_NOOP("MainWindow", "sprout")},
	Archetype{0xa7, QT_TRANSLATE_NOOP("MainWindow", "Artorigus")},
	Archetype{0xa8, QT_TRANSLATE_NOOP("MainWindow", "Laundsallyn")},
	Archetype{0xa9, QT_TRANSLATE_NOOP("MainWindow", "Fluffal")},
	Archetype{0xaa, QT_TRANSLATE_NOOP("MainWindow", "Qli")},
	Archetype{0xab, QT_TRANSLATE_NOOP("MainWindow", "Deskbot")},
	Archetype{0xac, QT_TRANSLATE_NOOP("MainWindow", "Goblin")},
	Archetype{0xad, QT_TRANSLATE_NOOP("MainWindow", "Frightfur")},
	Archetype{0xae, QT_TRANSLATE_NOOP("MainWindow", "Dark Contract")},
	Archetype{0xaf, QT_TRANSLATE_NOOP("MainWindow", "D/D")},
	Archetype{0xb, QT_TRANSLATE_NOOP("MainWindow", "Infernity")},
	Archetype{0xb0, QT_TRANSLATE_NOOP("MainWindow", "Gottoms")},
	Archetype{0xb1, QT_TRANSLATE_NOOP("MainWindow", "Burning Abyss")},
	Archetype{0xb2, QT_TRANSLATE_NOOP("MainWindow", "U.A.")},
	Archetype{0xb3, QT_TRANSLATE_NOOP("MainWindow", "Yosenju")},
	Archetype{0xb4, QT_TRANSLATE_NOOP("MainWindow", "Nekroz")},
	Archetype{0xb5, QT_TRANSLATE_NOOP("MainWindow", "Ritual Beast")},
	Archetype{0xb7, QT_TRANSLATE_NOOP("MainWindow", "Entity")},
	Archetype{0xb9, QT_TRANSLATE_NOOP("MainWindow", "Blaze Accelerator")},
	Archetype{0xba, QT_TRANSLATE_NOOP("MainWindow", "Raidraptor")},
	Archetype{0xbb, QT_TRANSLATE_NOOP("MainWindow", "Infernoid")},
	Archetype{0xbc, QT_TRANSLATE_NOOP("MainWindow", "Jinzo")},
	Archetype{0xbd, QT_TRANSLATE_NOOP("MainWindow", "Gaia The Fierce Knight")},
	Archetype{0xbe, QT_TRANSLATE_NOOP("MainWindow", "Monarch")},
	Archetype{0xbf, QT_TRANSLATE_NOOP("MainWindow", "Charmer")},
	Archetype{0xc, QT_TRANSLATE_NOOP("MainWindow", "Alien")},
	Archetype{0xc0, QT_TRANSLATE_NOOP("MainWindow", "Possessed")},
	Archetype{0xc008, QT_TRANSLATE_NOOP("MainWindow", "Destiny HERO")},
	Archetype{0xc1, QT_TRANSLATE_NOOP("MainWindow", "PSY-Frame")},
	Archetype{0xc2, QT_TRANSLATE_NOOP("MainWindow", "Power Tool")},
	Archetype{0xc3, QT_TRANSLATE_NOOP("MainWindow", "Edge Imp")},
	Archetype{0xc4, QT_TRANSLATE_NOOP("MainWindow", "Zefra")},
	Archetype{0xc5, QT_TRANSLATE_NOOP("MainWindow", "Void")},
	Archetype{0xc6, QT_TRANSLATE_NOOP("MainWindow", "Performage")},
	Archetype{0xc7, QT_TRANSLATE_NOOP("MainWindow", "Dracoslayer")},
	Archetype{0xc8, QT_TRANSLATE_NOOP("MainWindow", "Igknight")},
	Archetype{0xc9, QT_TRANSLATE_NOOP("MainWindow", "Aroma")},
	Archetype{0xca, QT_TRANSLATE_NOOP("MainWindow", "Empowered Warrior")},
	Archetype{0xcb, QT_TRANSLATE_NOOP("MainWindow", "Aether")},
	Archetype{0xcc, QT_TRANSLATE_NOOP("MainWindow", "Prediction Princess")},
	Archetype{0xcd, QT_TRANSLATE_NOOP("MainWindow", "Aqua")},
	Archetype{0xcf, QT_TRANSLATE_NOOP("MainWindow", "Chaos")},
	Archetype{0xd, QT_TRANSLATE_NOOP("MainWindow", "Saber")},
	Archetype{0xd0, QT_TRANSLATE_NOOP("MainWindow", "Majespecter")},
	Archetype{0xd1, QT_TRANSLATE_NOOP("MainWindow", "Graydle")},
	Archetype{0xd2, QT_TRANSLATE_NOOP("MainWindow", "Kozmo")},
	Archetype{0xd3, QT_TRANSLATE_NOOP("MainWindow", "Kaiju")},
	Archetype{0xd4, QT_TRANSLATE_NOOP("MainWindow", "Paleozoic")},
	Archetype{0xd5, QT_TRANSLATE_NOOP("MainWindow", "Dante")},
	Archetype{0xd6, QT_TRANSLATE_NOOP("MainWindow", "Destruction Sword")},
	Archetype{0xd7, QT_TRANSLATE_NOOP("MainWindow", "Buster Blader")},
	Archetype{0xd8, QT_TRANSLATE_NOOP("MainWindow", "Dinomist")},
	Archetype{0xd9, QT_TRANSLATE_NOOP("MainWindow", "Shiranui")},
	Archetype{0xda, QT_TRANSLATE_NOOP("MainWindow", "Dracoverlord")},
	Archetype{0xdb, QT_TRANSLATE_NOOP("MainWindow", "Phantom Knights")},
	Archetype{0xdc, QT_TRANSLATE_NOOP("MainWindow", "Super Quant")},
	Archetype{0xdd, QT_TRANSLATE_NOOP("MainWindow", "Blue-Eyes")},
	Archetype{0xde, QT_TRANSLATE_NOOP("MainWindow", "Exodia")},
	Archetype{0xdf, QT_TRANSLATE_NOOP("MainWindow", "Lunalight")},
	Archetype{0xe, QT_TRANSLATE_NOOP("MainWindow", "Watt")},
	Archetype{0xe0, QT_TRANSLATE_NOOP("MainWindow", "Amorphage")},
	Archetype{0xe1, QT_TRANSLATE_NOOP("MainWindow", "Metalfoes")},
	Archetype{0xe2, QT_TRANSLATE_NOOP("MainWindow", "Triamid")},
	Archetype{0xe3, QT_TRANSLATE_NOOP("MainWindow", "Cubic")},
	Archetype{0xe4, QT_TRANSLATE_NOOP("MainWindow", "Celtic Guard")},
	Archetype{0xe5, QT_TRANSLATE_NOOP("MainWindow", "Cipher")},
	Archetype{0xe6, QT_TRANSLATE_NOOP("MainWindow", "Flower Cardian")},
	Archetype{0xe7, QT_TRANSLATE_NOOP("MainWindow", "Silent Swordsman")},
	Archetype{0xe8, QT_TRANSLATE_NOOP("MainWindow", "Silent Magician")},
	Archetype{0xe9, QT_TRANSLATE_NOOP("MainWindow", "Magna Warrior")},
	Archetype{0xea, QT_TRANSLATE_NOOP("MainWindow", "Crystron")},
	Archetype{0xeb, QT_TRANSLATE_NOOP("MainWindow", "Chemicritter")},
	Archetype{0xec, QT_TRANSLATE_NOOP("MainWindow", "Abyss")},
	Archetype{0xed, QT_TRANSLATE_NOOP("MainWindow", "Subterror")},
	Archetype{0xee, QT_TRANSLATE_NOOP("MainWindow", "SPYRAL")},
	Archetype{0xef, QT_TRANSLATE_NOOP("MainWindow", "Darklord")},
	Archetype{0xf, QT_TRANSLATE_NOOP("MainWindow", "Ojama")},
	Archetype{0xf0, QT_TRANSLATE_NOOP("MainWindow", "Windwitch")},
	Archetype{0xf1, QT_TRANSLATE_NOOP("MainWindow", "Zoodiac")},
	Archetype{0xf2, QT_TRANSLATE_NOOP("MainWindow", "Pendulum")},
	Archetype{0xf3, QT_TRANSLATE_NOOP("MainWindow", "Predap")},
	Archetype{0xf4, QT_TRANSLATE_NOOP("MainWindow", "Invoked")},
	Archetype{0xf5, QT_TRANSLATE_NOOP("MainWindow", "Gandora")},
	Archetype{0xf6, QT_TRANSLATE_NOOP("MainWindow", "Skyscraper")},
	Archetype{0xf7, QT_TRANSLATE_NOOP("MainWindow", "Lyrilusc")},
	Archetype{0xf8, QT_TRANSLATE_NOOP("MainWindow", "Supreme King")},
	Archetype{0xf9, QT_TRANSLATE_NOOP("MainWindow", "True Draco|True King")},
	Archetype{0xfa, QT_TRANSLATE_NOOP("MainWindow", "Phantasm Spiral")},
	Archetype{0xfb, QT_TRANSLATE_NOOP("MainWindow", "Trickstar")},
	Archetype{0xfc, QT_TRANSLATE_NOOP("MainWindow", "Gouki")},
	Archetype{0xfd, QT_TRANSLATE_NOOP("MainWindow", "World Chalice")},
	Archetype{0xfe, QT_TRANSLATE_NOOP("MainWindow", "World Legacy")},
	Archetype{0xff, QT_TRANSLATE_NOOP("MainWindow", "Clear Wing")},
};

#endif // ARCHETYPES_HPP
