#ifndef ARCHETYPES_HPP
#define ARCHETYPES_HPP
#include <QMap>
#include <QtGlobal> // quint16
#include <utility>

using Archetype = std::pair<quint16, char const*>;

static QMap<quint16, char const*> const ARCHETYPES_MAP{
	Archetype{0x1, QT_TR_NOOP("Ally of Justice")},
	Archetype{0x10, QT_TR_NOOP("Gusto")},
	Archetype{0x100, QT_TR_NOOP("Bonding -")},
	Archetype{0x1002, QT_TR_NOOP("R-Genex")},
	Archetype{0x100a, QT_TR_NOOP("Steelswarm")},
	Archetype{0x100d, QT_TR_NOOP("X-Saber")},
	Archetype{0x101, QT_TR_NOOP("Code Talker")},
	Archetype{0x1016, QT_TR_NOOP("Vehicroid")},
	Archetype{0x1017, QT_TR_NOOP("Synchron")},
	Archetype{0x101b, QT_TR_NOOP("Mecha Phantom Beast")},
	Archetype{0x102, QT_TR_NOOP("Rokket")},
	Archetype{0x102b, QT_TR_NOOP("Armor Ninja")},
	Archetype{0x103, QT_TR_NOOP("Altergeist")},
	Archetype{0x1033, QT_TR_NOOP("Assault Blackwing")},
	Archetype{0x1034, QT_TR_NOOP("Crystal Beast")},
	Archetype{0x103d, QT_TR_NOOP("Secret Six Samurai")},
	Archetype{0x104, QT_TR_NOOP("Krawler")},
	Archetype{0x1045, QT_TR_NOOP("Red Dragon Archfiend")},
	Archetype{0x1046, QT_TR_NOOP("Fusion Dragon")},
	Archetype{0x1047, QT_TR_NOOP("Gem-Knight")},
	Archetype{0x1048, QT_TR_NOOP("Number C")},
	Archetype{0x104f, QT_TR_NOOP("/Assault Mode")},
	Archetype{0x105, QT_TR_NOOP("Metaphys")},
	Archetype{0x1050, QT_TR_NOOP("Starving Venom")},
	Archetype{0x1052, QT_TR_NOOP("Gate Guardian")},
	Archetype{0x106, QT_TR_NOOP("Vendread")},
	Archetype{0x1066, QT_TR_NOOP("Symphonic Warrior")},
	Archetype{0x106d, QT_TR_NOOP("Djinn of Rituals")},
	Archetype{0x106e, QT_TR_NOOP("Spellbook")},
	Archetype{0x106f, QT_TR_NOOP("Heroic Challenger")},
	Archetype{0x107, QT_TR_NOOP("F.A.")},
	Archetype{0x1072, QT_TR_NOOP("Geargiano")},
	Archetype{0x1073, QT_TR_NOOP("CXyz")},
	Archetype{0x107a, QT_TR_NOOP("Noble Knight")},
	Archetype{0x107b, QT_TR_NOOP("Galaxy-Eyes")},
	Archetype{0x107d, QT_TR_NOOP("Hazy Flame")},
	Archetype{0x107e, QT_TR_NOOP("ZW -")},
	Archetype{0x107f, QT_TR_NOOP("Utopia")},
	Archetype{0x108, QT_TR_NOOP("Magical Musket")},
	Archetype{0x1081, QT_TR_NOOP("Fire King Avatar")},
	Archetype{0x1083, QT_TR_NOOP("Gimmick Puppet")},
	Archetype{0x108a, QT_TR_NOOP("Traptrix")},
	Archetype{0x109, QT_TR_NOOP("The Weather")},
	Archetype{0x1093, QT_TR_NOOP("Cyber Dragon")},
	Archetype{0x109a, QT_TR_NOOP("Superheavy Samurai Soul")},
	Archetype{0x109b, QT_TR_NOOP("Melodious Maestra")},
	Archetype{0x109c, QT_TR_NOOP("Stellarknight")},
	Archetype{0x10a, QT_TR_NOOP("Parshath")},
	Archetype{0x10a2, QT_TR_NOOP("Dark Magician")},
	Archetype{0x10a4, QT_TR_NOOP("Winged Kuriboh")},
	Archetype{0x10aa, QT_TR_NOOP("Apoqliphort")},
	Archetype{0x10af, QT_TR_NOOP("D/D/D")},
	Archetype{0x10b, QT_TR_NOOP("Tindangle")},
	Archetype{0x10b5, QT_TR_NOOP("Ritual Beast Tamer")},
	Archetype{0x10b7, QT_TR_NOOP("Outer Entity")},
	Archetype{0x10c, QT_TR_NOOP("Mekk-Knight")},
	Archetype{0x10c0, QT_TR_NOOP("Familiar-Possessed")},
	Archetype{0x10c1, QT_TR_NOOP("PSY-Framegear")},
	Archetype{0x10cd, QT_TR_NOOP("Aquaactress")},
	Archetype{0x10cf, QT_TR_NOOP("Black Luster Soldier")},
	Archetype{0x10d, QT_TR_NOOP("Mythical Beast")},
	Archetype{0x10d9, QT_TR_NOOP("Shiranui Spectralsword")},
	Archetype{0x10db, QT_TR_NOOP("The Phantom Knights")},
	Archetype{0x10dc, QT_TR_NOOP("Super Quantum")},
	Archetype{0x10e, QT_TR_NOOP("Evolution Pill")},
	Archetype{0x10e3, QT_TR_NOOP("Cubic Seed")},
	Archetype{0x10e5, QT_TR_NOOP("Cipher Dragon")},
	Archetype{0x10ec, QT_TR_NOOP("Abyss Actor")},
	Archetype{0x10ed, QT_TR_NOOP("Subterror Behemoth")},
	Archetype{0x10ee, QT_TR_NOOP("SPYRAL GEAR")},
	Archetype{0x10f, QT_TR_NOOP("Borrel")},
	Archetype{0x10f2, QT_TR_NOOP("Pendulum Dragon")},
	Archetype{0x10f3, QT_TR_NOOP("Predaplant")},
	Archetype{0x10f8, QT_TR_NOOP("Supreme King Gate")},
	Archetype{0x11, QT_TR_NOOP("Karakuri")},
	Archetype{0x110, QT_TR_NOOP("Relinquished")},
	Archetype{0x111, QT_TR_NOOP("Armed Dragon")},
	Archetype{0x1110, QT_TR_NOOP("Eyes Restrict")},
	Archetype{0x1115, QT_TR_NOOP("Sky Striker Ace")},
	Archetype{0x112, QT_TR_NOOP("Knightmare")},
	Archetype{0x1123, QT_TR_NOOP("Rose Dragon")},
	Archetype{0x113, QT_TR_NOOP("Elemental Lord")},
	Archetype{0x1130, QT_TR_NOOP("Unchained Soul")},
	Archetype{0x114, QT_TR_NOOP("Fur Hire")},
	Archetype{0x114b, QT_TR_NOOP("Numeron Gate")},
	Archetype{0x115, QT_TR_NOOP("Sky Striker")},
	Archetype{0x1150, QT_TR_NOOP("Virtual World Gate")},
	Archetype{0x1157, QT_TR_NOOP("Sunavalon")},
	Archetype{0x116, QT_TR_NOOP("Crusadia")},
	Archetype{0x1164, QT_TR_NOOP("GranSolfachord")},
	Archetype{0x1169, QT_TR_NOOP("Mystical Beast of the Forest")},
	Archetype{0x117, QT_TR_NOOP("Impcantation")},
	Archetype{0x1178, QT_TR_NOOP("Barian's")},
	Archetype{0x117f, QT_TR_NOOP("Welcome Labrynth")},
	Archetype{0x118, QT_TR_NOOP("Cynet")},
	Archetype{0x1186, QT_TR_NOOP("Doodle Beast")},
	Archetype{0x119, QT_TR_NOOP("Salamangreat")},
	Archetype{0x11a, QT_TR_NOOP("Dinowrestler")},
	Archetype{0x11b, QT_TR_NOOP("Orcust")},
	Archetype{0x11c, QT_TR_NOOP("Thunder Dragon")},
	Archetype{0x11d, QT_TR_NOOP("Forbidden")},
	Archetype{0x11e, QT_TR_NOOP("Danger!")},
	Archetype{0x11f, QT_TR_NOOP("Nephthys")},
	Archetype{0x12, QT_TR_NOOP("Frog")},
	Archetype{0x120, QT_TR_NOOP("Prank-Kids")},
	Archetype{0x121, QT_TR_NOOP("Mayakashi")},
	Archetype{0x122, QT_TR_NOOP("Valkyrie")},
	Archetype{0x123, QT_TR_NOOP("Rose")},
	Archetype{0x124, QT_TR_NOOP("Machine Angel")},
	Archetype{0x125, QT_TR_NOOP("Smile")},
	Archetype{0x126, QT_TR_NOOP("Time Thief")},
	Archetype{0x127, QT_TR_NOOP("Infinitrack")},
	Archetype{0x128, QT_TR_NOOP("Witchcrafter")},
	Archetype{0x129, QT_TR_NOOP("Evil Eye")},
	Archetype{0x12a, QT_TR_NOOP("Endymion")},
	Archetype{0x12b, QT_TR_NOOP("Marincess")},
	Archetype{0x12c, QT_TR_NOOP("Tenyi")},
	Archetype{0x12d, QT_TR_NOOP("Simorgh")},
	Archetype{0x12e, QT_TR_NOOP("Fortune Fairy")},
	Archetype{0x12f, QT_TR_NOOP("Battlewasp")},
	Archetype{0x13, QT_TR_NOOP("Meklord")},
	Archetype{0x130, QT_TR_NOOP("Unchained")},
	Archetype{0x131, QT_TR_NOOP("Dream Mirror")},
	Archetype{0x132, QT_TR_NOOP("Mathmech")},
	Archetype{0x133, QT_TR_NOOP("Dragonmaid")},
	Archetype{0x134, QT_TR_NOOP("Generaider")},
	Archetype{0x135, QT_TR_NOOP("@Ignister")},
	Archetype{0x136, QT_TR_NOOP("A.I.")},
	Archetype{0x137, QT_TR_NOOP("Ancient Warriors")},
	Archetype{0x138, QT_TR_NOOP("Megalith")},
	Archetype{0x139, QT_TR_NOOP("Onomat")},
	Archetype{0x13a, QT_TR_NOOP("Palladium")},
	Archetype{0x13b, QT_TR_NOOP("Rebellion")},
	Archetype{0x13c, QT_TR_NOOP("Codebreaker")},
	Archetype{0x13d, QT_TR_NOOP("Nemeses")},
	Archetype{0x13e, QT_TR_NOOP("Barbaros")},
	Archetype{0x13f, QT_TR_NOOP("Plunder Patroll")},
	Archetype{0x14, QT_TR_NOOP("Allure Queen")},
	Archetype{0x140, QT_TR_NOOP("Adamancipator")},
	Archetype{0x141, QT_TR_NOOP("Rikka")},
	Archetype{0x142, QT_TR_NOOP("Eldlich")},
	Archetype{0x143, QT_TR_NOOP("Eldlixir")},
	Archetype{0x144, QT_TR_NOOP("Golden Land")},
	Archetype{0x145, QT_TR_NOOP("Phantasm")},
	Archetype{0x146, QT_TR_NOOP("Dogmatika")},
	Archetype{0x147, QT_TR_NOOP("Melffy")},
	Archetype{0x148, QT_TR_NOOP("Potan")},
	Archetype{0x149, QT_TR_NOOP("Roland")},
	Archetype{0x14a, QT_TR_NOOP("Appliancer")},
	Archetype{0x14b, QT_TR_NOOP("Numeron")},
	Archetype{0x14c, QT_TR_NOOP("Fossil")},
	Archetype{0x14d, QT_TR_NOOP("Spiritual Art")},
	Archetype{0x14e, QT_TR_NOOP("Dual Avatar")},
	Archetype{0x14f, QT_TR_NOOP("Tri-Brigade")},
	Archetype{0x15, QT_TR_NOOP("B.E.S.")},
	Archetype{0x150, QT_TR_NOOP("Virtual World")},
	Archetype{0x1509, QT_TR_NOOP("Barian's")},
	Archetype{0x150c, QT_TR_NOOP("Phantom Butterfly")},
	Archetype{0x150e, QT_TR_NOOP("Cat Girl")},
	Archetype{0x151, QT_TR_NOOP("Drytron")},
	Archetype{0x1512, QT_TR_NOOP("Royal Cookpal")},
	Archetype{0x1517, QT_TR_NOOP("Doll Monster")},
	Archetype{0x1518, QT_TR_NOOP("Doodle Beast")},
	Archetype{0x151a, QT_TR_NOOP("Earthbound")},
	Archetype{0x151b, QT_TR_NOOP("Magic Elf")},
	Archetype{0x152, QT_TR_NOOP("Magistus")},
	Archetype{0x1521, QT_TR_NOOP("Fossil Knight")},
	Archetype{0x1524, QT_TR_NOOP("Granel Attack")},
	Archetype{0x152c, QT_TR_NOOP("Jester Puppet")},
	Archetype{0x152f, QT_TR_NOOP("Champion")},
	Archetype{0x153, QT_TR_NOOP("Ki-sikil")},
	Archetype{0x1530, QT_TR_NOOP("Clock Knight")},
	Archetype{0x1538, QT_TR_NOOP("Stray Cat")},
	Archetype{0x154, QT_TR_NOOP("Lil-la")},
	Archetype{0x1541, QT_TR_NOOP("Quiz Panel")},
	Archetype{0x1549, QT_TR_NOOP("Skiel Attack")},
	Archetype{0x154a, QT_TR_NOOP("Angel")},
	Archetype{0x154d, QT_TR_NOOP("Spell Spice")},
	Archetype{0x154e, QT_TR_NOOP("Spirit Gem")},
	Archetype{0x155, QT_TR_NOOP("Evil★Twin")},
	Archetype{0x1550, QT_TR_NOOP("Pendulumstatue")},
	Archetype{0x1555, QT_TR_NOOP("Tachyon Dragon")},
	Archetype{0x155a, QT_TR_NOOP("\" V \"/\" V \"")},
	Archetype{0x155d, QT_TR_NOOP("White Knight")},
	Archetype{0x156, QT_TR_NOOP("Live☆Twin")},
	Archetype{0x1560, QT_TR_NOOP("Wisel Attack")},
	Archetype{0x157, QT_TR_NOOP("Sun")},
	Archetype{0x158, QT_TR_NOOP("Springans")},
	Archetype{0x159, QT_TR_NOOP("Myutant")},
	Archetype{0x15a, QT_TR_NOOP("S-Force")},
	Archetype{0x15b, QT_TR_NOOP("Starry Knight")},
	Archetype{0x15c, QT_TR_NOOP("Doll Monster")},
	Archetype{0x15d, QT_TR_NOOP("Rank-Down-Magic")},
	Archetype{0x15e, QT_TR_NOOP("Amazement")},
	Archetype{0x15f, QT_TR_NOOP("Attraction")},
	Archetype{0x16, QT_TR_NOOP("roid")},
	Archetype{0x160, QT_TR_NOOP("Branded")},
	Archetype{0x161, QT_TR_NOOP("War Rock")},
	Archetype{0x162, QT_TR_NOOP("Materiactor")},
	Archetype{0x163, QT_TR_NOOP("Ogdoadic")},
	Archetype{0x164, QT_TR_NOOP("Solfachord")},
	Archetype{0x165, QT_TR_NOOP("Ursarctic")},
	Archetype{0x166, QT_TR_NOOP("Despia")},
	Archetype{0x167, QT_TR_NOOP("Magikey")},
	Archetype{0x168, QT_TR_NOOP("Gunkan")},
	Archetype{0x169, QT_TR_NOOP("of the Forest")},
	Archetype{0x16a, QT_TR_NOOP("Stealth Kragen")},
	Archetype{0x16b, QT_TR_NOOP("Numerounius")},
	Archetype{0x16c, QT_TR_NOOP("Number")},
	Archetype{0x16d, QT_TR_NOOP("Swordsoul")},
	Archetype{0x16e, QT_TR_NOOP("Icejade")},
	Archetype{0x16f, QT_TR_NOOP("Floowandereeze")},
	Archetype{0x17, QT_TR_NOOP("Synchro")},
	Archetype{0x170, QT_TR_NOOP("Topologic")},
	Archetype{0x171, QT_TR_NOOP("Hyperion")},
	Archetype{0x172, QT_TR_NOOP("Beetrooper")},
	Archetype{0x173, QT_TR_NOOP("P.U.N.K.")},
	Archetype{0x174, QT_TR_NOOP("Exosister")},
	Archetype{0x174, QT_TR_NOOP("Exosister")},
	Archetype{0x175, QT_TR_NOOP("Dinomorphia")},
	Archetype{0x176, QT_TR_NOOP("Lady of Lament")},
	Archetype{0x177, QT_TR_NOOP("Seventh")},
	Archetype{0x178, QT_TR_NOOP("Barian")},
	Archetype{0x179, QT_TR_NOOP("Kairyu-Shin")},
	Archetype{0x17a, QT_TR_NOOP("Sea Stealth")},
	Archetype{0x17b, QT_TR_NOOP("Therion")},
	Archetype{0x17c, QT_TR_NOOP("Scareclaw")},
	Archetype{0x17d, QT_TR_NOOP("Libromancer")},
	Archetype{0x17e, QT_TR_NOOP("Vaylantz")},
	Archetype{0x17f, QT_TR_NOOP("Labrynth")},
	Archetype{0x18, QT_TR_NOOP("Cloudian")},
	Archetype{0x180, QT_TR_NOOP("Runick")},
	Archetype{0x181, QT_TR_NOOP("Spright")},
	Archetype{0x182, QT_TR_NOOP("Tearlaments")},
	Archetype{0x183, QT_TR_NOOP("Vernusylph")},
	Archetype{0x184, QT_TR_NOOP("Mokey Mokey")},
	Archetype{0x185, QT_TR_NOOP("Wingman")},
	Archetype{0x186, QT_TR_NOOP("Doodle")},
	Archetype{0x187, QT_TR_NOOP("G Golem")},
	Archetype{0x188, QT_TR_NOOP("Rainbow Bridge")},
	Archetype{0x189, QT_TR_NOOP("Byssted")},
	Archetype{0x189, QT_TR_NOOP("Bystial")},
	Archetype{0x18a, QT_TR_NOOP("Kashtira")},
	Archetype{0x18a, QT_TR_NOOP("Kshatri-La")},
	Archetype{0x18b, QT_TR_NOOP("Ghoti")},
	Archetype{0x18c, QT_TR_NOOP("Rescue-ACE")},
	Archetype{0x18d, QT_TR_NOOP("Purery")},
	Archetype{0x18d, QT_TR_NOOP("Purrely")},
	Archetype{0x18e, QT_TR_NOOP("Mikanko")},
	Archetype{0x18f, QT_TR_NOOP("Aquamirror")},
	Archetype{0x19, QT_TR_NOOP("Gladiator Beast")},
	Archetype{0x190, QT_TR_NOOP("Firewall")},
	Archetype{0x191, QT_TR_NOOP("Manadome")},
	Archetype{0x192, QT_TR_NOOP("Nemurelia")},
	Archetype{0x193, QT_TR_NOOP("Gold Pride")},
	Archetype{0x194, QT_TR_NOOP("Labyrinth Wall")},
	Archetype{0x195, QT_TR_NOOP("Favorite")},
	Archetype{0x196, QT_TR_NOOP("Vanquish Soul")},
	Archetype{0x197, QT_TR_NOOP("Nouvelles")},
	Archetype{0x198, QT_TR_NOOP("Recipe")},
	Archetype{0x1a, QT_TR_NOOP("Dark Scorpion")},
	Archetype{0x1b, QT_TR_NOOP("Phantom Beast")},
	Archetype{0x1c, QT_TR_NOOP("Spirit Message")},
	Archetype{0x1d, QT_TR_NOOP("Koa'ki Meiru")},
	Archetype{0x1e, QT_TR_NOOP("Chrysalis")},
	Archetype{0x1f, QT_TR_NOOP("Neo-Spacian")},
	Archetype{0x2, QT_TR_NOOP("Genex")},
	Archetype{0x20, QT_TR_NOOP("Shien")},
	Archetype{0x2002, QT_TR_NOOP("Genex Ally")},
	Archetype{0x2016, QT_TR_NOOP("Speedroid")},
	Archetype{0x2017, QT_TR_NOOP("Synchro Dragon")},
	Archetype{0x2033, QT_TR_NOOP("Blackwing Tamer")},
	Archetype{0x2034, QT_TR_NOOP("Ultimate Crystal")},
	Archetype{0x2048, QT_TR_NOOP("Number S")},
	Archetype{0x2066, QT_TR_NOOP("Magnet Warrior")},
	Archetype{0x206f, QT_TR_NOOP("Heroic Champion")},
	Archetype{0x2073, QT_TR_NOOP("Xyz Dragon")},
	Archetype{0x207a, QT_TR_NOOP("Noble Arms")},
	Archetype{0x207e, QT_TR_NOOP("ZS -")},
	Archetype{0x207f, QT_TR_NOOP("Utopic Future")},
	Archetype{0x2093, QT_TR_NOOP("Cyber Angel")},
	Archetype{0x209b, QT_TR_NOOP("Melodious Songstress")},
	Archetype{0x20a2, QT_TR_NOOP("Magician Girl")},
	Archetype{0x20b5, QT_TR_NOOP("Spiritual Beast")},
	Archetype{0x20b7, QT_TR_NOOP("Elder Entity")},
	Archetype{0x20cd, QT_TR_NOOP("Aquarium")},
	Archetype{0x20dc, QT_TR_NOOP("Super Quantal Mech Beast")},
	Archetype{0x20ec, QT_TR_NOOP("Abyss Script")},
	Archetype{0x20ee, QT_TR_NOOP("SPYRAL MISSION")},
	Archetype{0x20f2, QT_TR_NOOP("Pendulumgraph")},
	Archetype{0x20f8, QT_TR_NOOP("Supreme King Dragon")},
	Archetype{0x21, QT_TR_NOOP("Earthbound Immortal")},
	Archetype{0x2157, QT_TR_NOOP("Sunvine")},
	Archetype{0x2169, QT_TR_NOOP("Mystical Spirit of the Forest")},
	Archetype{0x2178, QT_TR_NOOP("Battleguard")},
	Archetype{0x2186, QT_TR_NOOP("Doodlebook")},
	Archetype{0x22, QT_TR_NOOP("Jurrac")},
	Archetype{0x23, QT_TR_NOOP("Malefic")},
	Archetype{0x24, QT_TR_NOOP("Scrap")},
	Archetype{0x25, QT_TR_NOOP("Iron Chain")},
	Archetype{0x2509, QT_TR_NOOP("Battleguard")},
	Archetype{0x2517, QT_TR_NOOP("Doll Part")},
	Archetype{0x2521, QT_TR_NOOP("Cenozoic")},
	Archetype{0x2524, QT_TR_NOOP("Granel Guard")},
	Archetype{0x2549, QT_TR_NOOP("Skiel Guard")},
	Archetype{0x254a, QT_TR_NOOP("Celestial")},
	Archetype{0x2560, QT_TR_NOOP("Wisel Guard")},
	Archetype{0x26, QT_TR_NOOP("Morphtronic")},
	Archetype{0x27, QT_TR_NOOP("T.G.")},
	Archetype{0x28, QT_TR_NOOP("Batteryman")},
	Archetype{0x29, QT_TR_NOOP("Dragunity")},
	Archetype{0x293, QT_TR_NOOP("Visas")},
	Archetype{0x294, QT_TR_NOOP("Counter")},
	Archetype{0x295, QT_TR_NOOP("Battlin' Boxing")},
	Archetype{0x2a, QT_TR_NOOP("Naturia")},
	Archetype{0x2b, QT_TR_NOOP("Ninja")},
	Archetype{0x2c, QT_TR_NOOP("Flamvell")},
	Archetype{0x2d, QT_TR_NOOP("Nitro")},
	Archetype{0x2e, QT_TR_NOOP("Gravekeeper's")},
	Archetype{0x2f, QT_TR_NOOP("Ice Barrier")},
	Archetype{0x3, QT_TR_NOOP("Horus the Black Flame Dragon")},
	Archetype{0x30, QT_TR_NOOP("Vylon")},
	Archetype{0x3008, QT_TR_NOOP("Elemental HERO")},
	Archetype{0x300d, QT_TR_NOOP("XX-Saber")},
	Archetype{0x3013, QT_TR_NOOP("Meklord Emperor")},
	Archetype{0x3042, QT_TR_NOOP("Nordic Ascendant")},
	Archetype{0x304e, QT_TR_NOOP("Evoltile")},
	Archetype{0x307b, QT_TR_NOOP("Galaxy-Eyes Tachyon Dragon")},
	Archetype{0x30a2, QT_TR_NOOP("Dark Magician Girl")},
	Archetype{0x30b5, QT_TR_NOOP("Spiritual Beast Tamer")},
	Archetype{0x31, QT_TR_NOOP("Fortune Lady")},
	Archetype{0x314d, QT_TR_NOOP("Spiritual Earth Art")},
	Archetype{0x316, QT_TR_NOOP("Darkness")},
	Archetype{0x32, QT_TR_NOOP("Volcanic")},
	Archetype{0x33, QT_TR_NOOP("Blackwing")},
	Archetype{0x34, QT_TR_NOOP("Crystal")},
	Archetype{0x35, QT_TR_NOOP("Fabled")},
	Archetype{0x351a, QT_TR_NOOP("Earthbound Servant")},
	Archetype{0x3521, QT_TR_NOOP("Cenozoic Fossil Knight")},
	Archetype{0x36, QT_TR_NOOP("Machina")},
	Archetype{0x37, QT_TR_NOOP("Mist Valley")},
	Archetype{0x38, QT_TR_NOOP("Lightsworn")},
	Archetype{0x39, QT_TR_NOOP("Laval")},
	Archetype{0x3a, QT_TR_NOOP("Gishki")},
	Archetype{0x3b, QT_TR_NOOP("Red-Eyes")},
	Archetype{0x3c, QT_TR_NOOP("Reptilianne")},
	Archetype{0x3d, QT_TR_NOOP("Six Samurai")},
	Archetype{0x3e, QT_TR_NOOP("Worm")},
	Archetype{0x3f, QT_TR_NOOP("Majestic")},
	Archetype{0x4, QT_TR_NOOP("Amazoness")},
	Archetype{0x40, QT_TR_NOOP("Forbidden One")},
	Archetype{0x400d, QT_TR_NOOP("Elementsaber")},
	Archetype{0x407a, QT_TR_NOOP("Infernoble")},
	Archetype{0x4093, QT_TR_NOOP("Cyberdark")},
	Archetype{0x40b5, QT_TR_NOOP("Ritual Beast Ulti-")},
	Archetype{0x40b7, QT_TR_NOOP("Old Entity")},
	Archetype{0x40ec, QT_TR_NOOP("Abyss Costume")},
	Archetype{0x41, QT_TR_NOOP("LV")},
	Archetype{0x4157, QT_TR_NOOP("Sunseed")},
	Archetype{0x42, QT_TR_NOOP("Nordic")},
	Archetype{0x43, QT_TR_NOOP("Junk")},
	Archetype{0x44, QT_TR_NOOP("The Agent")},
	Archetype{0x45, QT_TR_NOOP("Archfiend")},
	Archetype{0x4521, QT_TR_NOOP("Mezozoic")},
	Archetype{0x4524, QT_TR_NOOP("Granel Top")},
	Archetype{0x4549, QT_TR_NOOP("Skiel Top")},
	Archetype{0x4560, QT_TR_NOOP("Wisel Top")},
	Archetype{0x46, QT_TR_NOOP("Polymerization|Fusion")},
	Archetype{0x47, QT_TR_NOOP("Gem-")},
	Archetype{0x48, QT_TR_NOOP("Number")},
	Archetype{0x49, QT_TR_NOOP("Skyblaster")},
	Archetype{0x4a, QT_TR_NOOP("Timelord")},
	Archetype{0x4b, QT_TR_NOOP("Aesir")},
	Archetype{0x4c, QT_TR_NOOP("Trap Hole")},
	Archetype{0x4d, QT_TR_NOOP("Beast's Battle")},
	Archetype{0x4e, QT_TR_NOOP("Evol")},
	Archetype{0x4f, QT_TR_NOOP("Dark Lucius")},
	Archetype{0x5, QT_TR_NOOP("Arcana Force")},
	Archetype{0x50, QT_TR_NOOP("Venom")},
	Archetype{0x500, QT_TR_NOOP("Speed Spell")},
	Archetype{0x5008, QT_TR_NOOP("Vision HERO")},
	Archetype{0x501, QT_TR_NOOP("Alchemy Beast")},
	Archetype{0x502, QT_TR_NOOP("Alligator")},
	Archetype{0x503, QT_TR_NOOP("Anti")},
	Archetype{0x5034, QT_TR_NOOP("Advanced Crystal Beast")},
	Archetype{0x504, QT_TR_NOOP("Assassin")},
	Archetype{0x5042, QT_TR_NOOP("Nordic Relic")},
	Archetype{0x5048, QT_TR_NOOP("Number C39")},
	Archetype{0x504e, QT_TR_NOOP("Evolzar")},
	Archetype{0x505, QT_TR_NOOP("Astral")},
	Archetype{0x506, QT_TR_NOOP("Atlandis")},
	Archetype{0x507, QT_TR_NOOP("Attack")},
	Archetype{0x507a, QT_TR_NOOP("Infernoble Knight")},
	Archetype{0x508, QT_TR_NOOP("Baby")},
	Archetype{0x509, QT_TR_NOOP("Barian")},
	Archetype{0x50b, QT_TR_NOOP("Beastborg")},
	Archetype{0x50c, QT_TR_NOOP("Butterfly")},
	Archetype{0x50d, QT_TR_NOOP("Carrier")},
	Archetype{0x50e, QT_TR_NOOP("Cat")},
	Archetype{0x50f, QT_TR_NOOP("Cicada")},
	Archetype{0x51, QT_TR_NOOP("Gadget")},
	Archetype{0x510, QT_TR_NOOP("Clear")},
	Archetype{0x511, QT_TR_NOOP("Comics Hero")},
	Archetype{0x512, QT_TR_NOOP("Cookpal")},
	Archetype{0x513, QT_TR_NOOP("Dart")},
	Archetype{0x514, QT_TR_NOOP("Dice")},
	Archetype{0x514d, QT_TR_NOOP("Spiritual Fire Art")},
	Archetype{0x515, QT_TR_NOOP("Dizzy")},
	Archetype{0x516, QT_TR_NOOP("Dog")},
	Archetype{0x517, QT_TR_NOOP("Doll")},
	Archetype{0x518, QT_TR_NOOP("Doodle")},
	Archetype{0x519, QT_TR_NOOP("Dyson")},
	Archetype{0x51a, QT_TR_NOOP("Earth")},
	Archetype{0x51b, QT_TR_NOOP("Elf")},
	Archetype{0x51d, QT_TR_NOOP("Fairy")},
	Archetype{0x51e, QT_TR_NOOP("Forbidden Beast")},
	Archetype{0x51f, QT_TR_NOOP("Forest")},
	Archetype{0x52, QT_TR_NOOP("Guardian")},
	Archetype{0x520, QT_TR_NOOP("Fortune Fairy")},
	Archetype{0x521, QT_TR_NOOP("Gaia the Dragon Champion")},
	Archetype{0x522, QT_TR_NOOP("Gorgonic")},
	Archetype{0x523, QT_TR_NOOP("Goyo")},
	Archetype{0x524, QT_TR_NOOP("Granel")},
	Archetype{0x525, QT_TR_NOOP("Guard")},
	Archetype{0x526, QT_TR_NOOP("Guts Master")},
	Archetype{0x527, QT_TR_NOOP("Hand")},
	Archetype{0x528, QT_TR_NOOP("Heart Monster")},
	Archetype{0x529, QT_TR_NOOP("Heavy Industry")},
	Archetype{0x52a, QT_TR_NOOP("Inu")},
	Archetype{0x52b, QT_TR_NOOP("Ivy")},
	Archetype{0x52c, QT_TR_NOOP("Jester")},
	Archetype{0x52d, QT_TR_NOOP("Jutte")},
	Archetype{0x52e, QT_TR_NOOP("Kabuki Stage")},
	Archetype{0x52f, QT_TR_NOOP("King")},
	Archetype{0x53, QT_TR_NOOP("Constellar")},
	Archetype{0x530, QT_TR_NOOP("Knight")},
	Archetype{0x531, QT_TR_NOOP("Koala")},
	Archetype{0x533, QT_TR_NOOP("Landstar")},
	Archetype{0x534, QT_TR_NOOP("Magnet")},
	Archetype{0x535, QT_TR_NOOP("Mantis")},
	Archetype{0x536, QT_TR_NOOP("Mosquito")},
	Archetype{0x537, QT_TR_NOOP("Motor")},
	Archetype{0x538, QT_TR_NOOP("Neko")},
	Archetype{0x53b, QT_TR_NOOP("Numeronius")},
	Archetype{0x53c, QT_TR_NOOP("Papillon")},
	Archetype{0x53d, QT_TR_NOOP("Parasite")},
	Archetype{0x53e, QT_TR_NOOP("Pixie")},
	Archetype{0x53f, QT_TR_NOOP("Priestess")},
	Archetype{0x54, QT_TR_NOOP("Gagaga")},
	Archetype{0x540, QT_TR_NOOP("Puppet")},
	Archetype{0x541, QT_TR_NOOP("Quiz")},
	Archetype{0x542, QT_TR_NOOP("Raccoon")},
	Archetype{0x543, QT_TR_NOOP("Red")},
	Archetype{0x545, QT_TR_NOOP("Seal")},
	Archetype{0x546, QT_TR_NOOP("Shaman")},
	Archetype{0x547, QT_TR_NOOP("Shark")},
	Archetype{0x548, QT_TR_NOOP("Shining")},
	Archetype{0x549, QT_TR_NOOP("Skiel")},
	Archetype{0x54a, QT_TR_NOOP("Sky")},
	Archetype{0x54b, QT_TR_NOOP("Slime")},
	Archetype{0x54c, QT_TR_NOOP("Sphere")},
	Archetype{0x54d, QT_TR_NOOP("Spice")},
	Archetype{0x54e, QT_TR_NOOP("Spirit")},
	Archetype{0x54f, QT_TR_NOOP("Starship")},
	Archetype{0x55, QT_TR_NOOP("Photon")},
	Archetype{0x550, QT_TR_NOOP("Statue")},
	Archetype{0x551, QT_TR_NOOP("Stone")},
	Archetype{0x552, QT_TR_NOOP("Strain")},
	Archetype{0x5521, QT_TR_NOOP("Mezozoic Fossil Knight")},
	Archetype{0x555, QT_TR_NOOP("Tachyon")},
	Archetype{0x556, QT_TR_NOOP("Thorn Prisoner")},
	Archetype{0x557, QT_TR_NOOP("Top")},
	Archetype{0x558, QT_TR_NOOP("Toy (Arc-V)")},
	Archetype{0x559, QT_TR_NOOP("Toy")},
	Archetype{0x55a, QT_TR_NOOP("V")},
	Archetype{0x55c, QT_TR_NOOP("Vigilante")},
	Archetype{0x55d, QT_TR_NOOP("White")},
	Archetype{0x55f, QT_TR_NOOP("Sinister Doctrine")},
	Archetype{0x56, QT_TR_NOOP("Inzektor")},
	Archetype{0x560, QT_TR_NOOP("Wisel")},
	Archetype{0x561, QT_TR_NOOP("Yubel")},
	Archetype{0x562, QT_TR_NOOP("∞")},
	Archetype{0x563, QT_TR_NOOP("Yomi")},
	Archetype{0x564, QT_TR_NOOP("Shogi|Line Monster")},
	Archetype{0x565, QT_TR_NOOP("Hunder")},
	Archetype{0x566, QT_TR_NOOP("Heraldic")},
	Archetype{0x567, QT_TR_NOOP("Hell")},
	Archetype{0x568, QT_TR_NOOP("C")},
	Archetype{0x569, QT_TR_NOOP("Eco Spell")},
	Archetype{0x56a, QT_TR_NOOP("Junk Robot")},
	Archetype{0x56b, QT_TR_NOOP("W")},
	Archetype{0x56c, QT_TR_NOOP("X")},
	Archetype{0x56d, QT_TR_NOOP("Y")},
	Archetype{0x56e, QT_TR_NOOP("Z")},
	Archetype{0x56f, QT_TR_NOOP("Dark Mummy")},
	Archetype{0x57, QT_TR_NOOP("Resonator")},
	Archetype{0x570, QT_TR_NOOP("Tentacluster")},
	Archetype{0x571, QT_TR_NOOP("Monarch (monster)")},
	Archetype{0x572, QT_TR_NOOP("Mirror Imagine")},
	Archetype{0x573, QT_TR_NOOP("Helixx")},
	Archetype{0x574, QT_TR_NOOP("Sunavalon")},
	Archetype{0x575, QT_TR_NOOP("Sunvine")},
	Archetype{0x576, QT_TR_NOOP("Starving Venemy")},
	Archetype{0x577, QT_TR_NOOP("Hydradrive")},
	Archetype{0x578, QT_TR_NOOP("Armatos Legio")},
	Archetype{0x579, QT_TR_NOOP("D-Scale")},
	Archetype{0x57a, QT_TR_NOOP("Appliancer")},
	Archetype{0x57b, QT_TR_NOOP("Topologina")},
	Archetype{0x58, QT_TR_NOOP("Wind-Up")},
	Archetype{0x580, QT_TR_NOOP("Stormrider")},
	Archetype{0x581, QT_TR_NOOP("Drone")},
	Archetype{0x583, QT_TR_NOOP("Mask")},
	Archetype{0x59, QT_TR_NOOP("Gogogo")},
	Archetype{0x5a, QT_TR_NOOP("Penguin")},
	Archetype{0x5b, QT_TR_NOOP("Inmato")},
	Archetype{0x5c, QT_TR_NOOP("Sphinx")},
	Archetype{0x5d, QT_TR_NOOP("Ultimate Insect")},
	Archetype{0x5e, QT_TR_NOOP("Dark Mimic")},
	Archetype{0x5f, QT_TR_NOOP("Mystic Swordsman")},
	Archetype{0x6, QT_TR_NOOP("Dark World")},
	Archetype{0x60, QT_TR_NOOP("Bamboo Sword")},
	Archetype{0x600, QT_TR_NOOP("Dark Tuner")},
	Archetype{0x6008, QT_TR_NOOP("Evil HERO")},
	Archetype{0x601, QT_TR_NOOP("Dark Synchro")},
	Archetype{0x6013, QT_TR_NOOP("Meklord Army")},
	Archetype{0x6042, QT_TR_NOOP("Nordic Beast")},
	Archetype{0x604e, QT_TR_NOOP("Evolsaur")},
	Archetype{0x607a, QT_TR_NOOP("Infernoble Arms")},
	Archetype{0x61, QT_TR_NOOP("Ninjitsu Art")},
	Archetype{0x614d, QT_TR_NOOP("Spiritual Water Art")},
	Archetype{0x62, QT_TR_NOOP("Toon")},
	Archetype{0x63, QT_TR_NOOP("Reactor")},
	Archetype{0x64, QT_TR_NOOP("Harpie")},
	Archetype{0x65, QT_TR_NOOP("Infestation")},
	Archetype{0x66, QT_TR_NOOP("Warrior")},
	Archetype{0x67, QT_TR_NOOP("Iron")},
	Archetype{0x67, QT_TR_NOOP("Koala")},
	Archetype{0x68, QT_TR_NOOP("Kangaroo")},
	Archetype{0x68, QT_TR_NOOP("Tin")},
	Archetype{0x69, QT_TR_NOOP("Hieratic")},
	Archetype{0x6a, QT_TR_NOOP("Butterspy")},
	Archetype{0x6b, QT_TR_NOOP("Bounzer")},
	Archetype{0x6c, QT_TR_NOOP("Lightray")},
	Archetype{0x6d, QT_TR_NOOP("Djinn")},
	Archetype{0x6e, QT_TR_NOOP("Prophecy")},
	Archetype{0x6f, QT_TR_NOOP("Heroic")},
	Archetype{0x7, QT_TR_NOOP("Ancient Gear")},
	Archetype{0x70, QT_TR_NOOP("Chronomaly")},
	Archetype{0x71, QT_TR_NOOP("Madolche")},
	Archetype{0x72, QT_TR_NOOP("Geargia")},
	Archetype{0x73, QT_TR_NOOP("Xyz")},
	Archetype{0x74, QT_TR_NOOP("Mermail")},
	Archetype{0x75, QT_TR_NOOP("Abyss-")},
	Archetype{0x76, QT_TR_NOOP("Heraldic Beast")},
	Archetype{0x77, QT_TR_NOOP("Atlantean")},
	Archetype{0x78, QT_TR_NOOP("Nimble")},
	Archetype{0x79, QT_TR_NOOP("Fire Fist")},
	Archetype{0x7a, QT_TR_NOOP("Noble")},
	Archetype{0x7b, QT_TR_NOOP("Galaxy")},
	Archetype{0x7c, QT_TR_NOOP("Fire Formation")},
	Archetype{0x7d, QT_TR_NOOP("Hazy")},
	Archetype{0x7e, QT_TR_NOOP("Zexal")},
	Archetype{0x7f, QT_TR_NOOP("Utopic")},
	Archetype{0x8, QT_TR_NOOP("HERO")},
	Archetype{0x80, QT_TR_NOOP("Duston")},
	Archetype{0x81, QT_TR_NOOP("Fire King")},
	Archetype{0x82, QT_TR_NOOP("Dododo")},
	Archetype{0x83, QT_TR_NOOP("Puppet")},
	Archetype{0x84, QT_TR_NOOP("Battlin' Boxer")},
	Archetype{0x85, QT_TR_NOOP("Super Defense Robot")},
	Archetype{0x8521, QT_TR_NOOP("Paleozoic")},
	Archetype{0x8524, QT_TR_NOOP("Granel Carrier")},
	Archetype{0x8549, QT_TR_NOOP("Skiel Carrier")},
	Archetype{0x8560, QT_TR_NOOP("Wisel Carrier")},
	Archetype{0x86, QT_TR_NOOP("Star Seraph")},
	Archetype{0x87, QT_TR_NOOP("Umbral Horror")},
	Archetype{0x88, QT_TR_NOOP("Bujin")},
	Archetype{0x89, QT_TR_NOOP("Hole")},
	Archetype{0x8a, QT_TR_NOOP("Envy")},
	Archetype{0x8b, QT_TR_NOOP("Malicevorous")},
	Archetype{0x8c, QT_TR_NOOP("Druid")},
	Archetype{0x8d, QT_TR_NOOP("Ghostrick")},
	Archetype{0x8e, QT_TR_NOOP("Vampire")},
	Archetype{0x8f, QT_TR_NOOP("Zubaba")},
	Archetype{0x9, QT_TR_NOOP("Neos")},
	Archetype{0x90, QT_TR_NOOP("Sylvan")},
	Archetype{0x9013, QT_TR_NOOP("Meklord Astro")},
	Archetype{0x91, QT_TR_NOOP("Necrovalley")},
	Archetype{0x92, QT_TR_NOOP("Heraldry")},
	Archetype{0x93, QT_TR_NOOP("Cyber")},
	Archetype{0x94, QT_TR_NOOP("Cybernetic")},
	Archetype{0x95, QT_TR_NOOP("Rank-Up-Magic")},
	Archetype{0x9521, QT_TR_NOOP("Paleozoic Fossil Knight")},
	Archetype{0x96, QT_TR_NOOP("Fishborg")},
	Archetype{0x97, QT_TR_NOOP("Artifact")},
	Archetype{0x98, QT_TR_NOOP("Magician")},
	Archetype{0x99, QT_TR_NOOP("Odd-Eyes")},
	Archetype{0x9a, QT_TR_NOOP("Superheavy Samurai")},
	Archetype{0x9b, QT_TR_NOOP("Melodious")},
	Archetype{0x9c, QT_TR_NOOP("tellarknight")},
	Archetype{0x9d, QT_TR_NOOP("Shaddoll")},
	Archetype{0x9e, QT_TR_NOOP("Yang Zing")},
	Archetype{0x9f, QT_TR_NOOP("Performapal")},
	Archetype{0xa, QT_TR_NOOP("lswarm")},
	Archetype{0xa0, QT_TR_NOOP("Legendary Knight")},
	Archetype{0xa008, QT_TR_NOOP("Masked HERO")},
	Archetype{0xa042, QT_TR_NOOP("Nordic Alfar")},
	Archetype{0xa1, QT_TR_NOOP("Legendary Dragon")},
	Archetype{0xa14d, QT_TR_NOOP("Spiritual Wind Art")},
	Archetype{0xa2, QT_TR_NOOP("Magician")},
	Archetype{0xa3, QT_TR_NOOP("Stardust")},
	Archetype{0xa4, QT_TR_NOOP("Kuriboh")},
	Archetype{0xa5, QT_TR_NOOP("Change")},
	Archetype{0xa6, QT_TR_NOOP("sprout")},
	Archetype{0xa7, QT_TR_NOOP("Artorigus")},
	Archetype{0xa8, QT_TR_NOOP("Laundsallyn")},
	Archetype{0xa9, QT_TR_NOOP("Fluffal")},
	Archetype{0xaa, QT_TR_NOOP("Qli")},
	Archetype{0xab, QT_TR_NOOP("Deskbot")},
	Archetype{0xac, QT_TR_NOOP("Goblin")},
	Archetype{0xad, QT_TR_NOOP("Frightfur")},
	Archetype{0xae, QT_TR_NOOP("Dark Contract")},
	Archetype{0xaf, QT_TR_NOOP("D/D")},
	Archetype{0xb, QT_TR_NOOP("Infernity")},
	Archetype{0xb0, QT_TR_NOOP("Gottoms")},
	Archetype{0xb1, QT_TR_NOOP("Burning Abyss")},
	Archetype{0xb2, QT_TR_NOOP("U.A.")},
	Archetype{0xb3, QT_TR_NOOP("Yosenju")},
	Archetype{0xb4, QT_TR_NOOP("Nekroz")},
	Archetype{0xb5, QT_TR_NOOP("Ritual Beast")},
	Archetype{0xb7, QT_TR_NOOP("Entity")},
	Archetype{0xb9, QT_TR_NOOP("Blaze Accelerator")},
	Archetype{0xba, QT_TR_NOOP("Raidraptor")},
	Archetype{0xbb, QT_TR_NOOP("Infernoid")},
	Archetype{0xbc, QT_TR_NOOP("Jinzo")},
	Archetype{0xbd, QT_TR_NOOP("Gaia The Fierce Knight")},
	Archetype{0xbe, QT_TR_NOOP("Monarch")},
	Archetype{0xbf, QT_TR_NOOP("Charmer")},
	Archetype{0xc, QT_TR_NOOP("Alien")},
	Archetype{0xc0, QT_TR_NOOP("Possessed")},
	Archetype{0xc008, QT_TR_NOOP("Destiny HERO")},
	Archetype{0xc1, QT_TR_NOOP("PSY-Frame")},
	Archetype{0xc2, QT_TR_NOOP("Power Tool")},
	Archetype{0xc3, QT_TR_NOOP("Edge Imp")},
	Archetype{0xc4, QT_TR_NOOP("Zefra")},
	Archetype{0xc5, QT_TR_NOOP("Void")},
	Archetype{0xc6, QT_TR_NOOP("Performage")},
	Archetype{0xc7, QT_TR_NOOP("Dracoslayer")},
	Archetype{0xc8, QT_TR_NOOP("Igknight")},
	Archetype{0xc9, QT_TR_NOOP("Aroma")},
	Archetype{0xca, QT_TR_NOOP("Empowered Warrior")},
	Archetype{0xcb, QT_TR_NOOP("Aether")},
	Archetype{0xcc, QT_TR_NOOP("Prediction Princess")},
	Archetype{0xcd, QT_TR_NOOP("Aqua")},
	Archetype{0xcf, QT_TR_NOOP("Chaos")},
	Archetype{0xd, QT_TR_NOOP("Saber")},
	Archetype{0xd0, QT_TR_NOOP("Majespecter")},
	Archetype{0xd1, QT_TR_NOOP("Graydle")},
	Archetype{0xd2, QT_TR_NOOP("Kozmo")},
	Archetype{0xd3, QT_TR_NOOP("Kaiju")},
	Archetype{0xd4, QT_TR_NOOP("Paleozoic")},
	Archetype{0xd5, QT_TR_NOOP("Dante")},
	Archetype{0xd6, QT_TR_NOOP("Destruction Sword")},
	Archetype{0xd7, QT_TR_NOOP("Buster Blader")},
	Archetype{0xd8, QT_TR_NOOP("Dinomist")},
	Archetype{0xd9, QT_TR_NOOP("Shiranui")},
	Archetype{0xda, QT_TR_NOOP("Dracoverlord")},
	Archetype{0xdb, QT_TR_NOOP("Phantom Knights")},
	Archetype{0xdc, QT_TR_NOOP("Super Quant")},
	Archetype{0xdd, QT_TR_NOOP("Blue-Eyes")},
	Archetype{0xde, QT_TR_NOOP("Exodia")},
	Archetype{0xdf, QT_TR_NOOP("Lunalight")},
	Archetype{0xe, QT_TR_NOOP("Watt")},
	Archetype{0xe0, QT_TR_NOOP("Amorphage")},
	Archetype{0xe1, QT_TR_NOOP("Metalfoes")},
	Archetype{0xe2, QT_TR_NOOP("Triamid")},
	Archetype{0xe3, QT_TR_NOOP("Cubic")},
	Archetype{0xe4, QT_TR_NOOP("Celtic Guard")},
	Archetype{0xe5, QT_TR_NOOP("Cipher")},
	Archetype{0xe6, QT_TR_NOOP("Flower Cardian")},
	Archetype{0xe7, QT_TR_NOOP("Silent Swordsman")},
	Archetype{0xe8, QT_TR_NOOP("Silent Magician")},
	Archetype{0xe9, QT_TR_NOOP("Magna Warrior")},
	Archetype{0xea, QT_TR_NOOP("Crystron")},
	Archetype{0xeb, QT_TR_NOOP("Chemicritter")},
	Archetype{0xec, QT_TR_NOOP("Abyss")},
	Archetype{0xed, QT_TR_NOOP("Subterror")},
	Archetype{0xee, QT_TR_NOOP("SPYRAL")},
	Archetype{0xef, QT_TR_NOOP("Darklord")},
	Archetype{0xf, QT_TR_NOOP("Ojama")},
	Archetype{0xf0, QT_TR_NOOP("Windwitch")},
	Archetype{0xf1, QT_TR_NOOP("Zoodiac")},
	Archetype{0xf2, QT_TR_NOOP("Pendulum")},
	Archetype{0xf3, QT_TR_NOOP("Predap")},
	Archetype{0xf4, QT_TR_NOOP("Invoked")},
	Archetype{0xf5, QT_TR_NOOP("Gandora")},
	Archetype{0xf6, QT_TR_NOOP("Skyscraper")},
	Archetype{0xf7, QT_TR_NOOP("Lyrilusc")},
	Archetype{0xf8, QT_TR_NOOP("Supreme King")},
	Archetype{0xf9, QT_TR_NOOP("True Draco|True King")},
	Archetype{0xfa, QT_TR_NOOP("Phantasm Spiral")},
	Archetype{0xfb, QT_TR_NOOP("Trickstar")},
	Archetype{0xfc, QT_TR_NOOP("Gouki")},
	Archetype{0xfd, QT_TR_NOOP("World Chalice")},
	Archetype{0xfe, QT_TR_NOOP("World Legacy")},
	Archetype{0xff, QT_TR_NOOP("Clear Wing")},
};

#endif // ARCHETYPES_HPP
